docs/next.config.js
docs/src/images/logo.svg
docs/src/siteConfig.js

This PR updates the prefix of docs and web to monika so that the landing page and the docs can be hosted in Github Pages correctly.

update the prefix of docs and web to monika

---

CODE_OF_CONDUCTS.md
LICENSE.txt
README.md

This PR:
- updates the README.md file.
- adds MIT License
- adds code of conducts guide file.

update readme and add license and code of conducts

---

.github/workflows/npm-publish.yml

This PR fixes the publishing to npm

fix npm publish

---

docs/src/components/Nav.js
docs/src/components/Seo.js
docs/src/pages/index.js

This PR
- replaces HTTPProbe strings with  Monika
- replaces TanStack string with Hyperjump Technology

replace all occurrences of HTTPProbe with Monika

---

README.md
package-lock.json

Added build badge into the README.md
Solved issue #28

Added build badge

---

config.example.json
src/index.ts
src/interfaces/data.ts
src/interfaces/notification.ts
src/utils/alert.ts
src/utils/notifications/slack.ts
src/utils/notifications/webhook.ts
src/utils/validate-config.ts
test/utils/alert.test.ts

feat: adds slack notification

---

docs/src/pages/guides/notifications.md

Some wording in notifications documentation are still not effective
Modify the phrasing of some words and fix it according some review
Go to Notifications documentation sections on Readme.

fix notifications docs phrases

---

package-lock.json
package.json

Currently Monika version is still show 0.0.0
Change version in package.json to 1.0.0
Run command `./bin/run -v`

core(version): change package version to 1.0.0

---

src/utils/validate-config.ts
test/index.test.ts
test/testConfigs/probes/duplicateProbeId.json

1. This PR implements #41 (Probe ID Validation issue)
1. check unique ids of probes config
2. if a duplicate is found, it will throw an error

feat: add probe id validation

---

docs/src/pages/index.js
docs/src/pages/quick-start.md

This PR updates the quick start guide so that user can quickly test Monika:
- Shows a step by step instruction on how to use Monika to monitor Monika's website.
- Shows a link to the quick start from landing page.

docs: update quick start guide

---

config.example.json
docs/src/pages/guides/probes.md
docs/src/pages/quick-start.md
src/index.ts
src/interfaces/config.ts
src/interfaces/probe.ts
src/utils/looper.ts
test/index.test.ts
test/testConfigs/invalidNotificationType.json
test/testConfigs/mailgun/mailgunconfig.json
test/testConfigs/mailgun/mailgunconfigNoRecipients.json
test/testConfigs/noNotifications.json
test/testConfigs/probes/noProbes.json
test/testConfigs/sendgrid/sendgridconfig.json
test/testConfigs/sendgrid/sendgridconfigNoRecipients.json
test/testConfigs/smtp/smtpconfig.json
test/testConfigs/smtp/smtpconfigNoRecipients.json
test/testConfigs/webhook/webhookconfig.json

feat: interval per-probe

---

package-lock.json
package.json
src/interfaces/probe-status.ts
src/utils/looper.ts
src/utils/process-server-status.ts

This PR fixes #65 
This PR solves the condition where there are multiple probes, the consecutive counts does not add up every request. This happened because of wrong algorithm.
1. Use this configuration:
```
{
"notifications": [
{
"id": "unique-id-smtp",
"type": "smtp",
"data": {
"recipients": ["recipient1@example.com"],
"hostname": "smtp.mailtrap.io",
"port": 2525,
"username": "a9356e48bc43ac",
"password": "c6a69a8822f56b"
}
}
],
"probes": [
{
"id": "1",
"name": "Monika",
"description": "Probe",
"interval": 5,
"request": {
"url": "https://hyperjumptech.github.io/monika",
"timeout": 7000
},
"trueThreshold": 2,
"falseThreshold": 2,
"alerts": ["status-not-2xx", "response-time-greater-than-200-ms"]
},
{
"id": "2",
"name": "Localhost",
"description": "Probe",
"interval": 5,
"request": { …
```

Handle Notifications not Sent when Defining Multiple Probes

---

CHANGELOG.md
package.json

Preparing release 1.1.0
- Bumping up version in package.json
- Bumping up version 1.1.0 in Dockerfile
- Added notes in CHANGELOG.md

Increased version to 1.1.0 for next release

---

package-lock.json
package.json
scripts/preinstall.js

this PR fixes failure when installing monika globally through npm

fix: add /scripts to included files

---

package-lock.json
package.json

fix: add missing package

---

package-lock.json
package.json
src/index.ts
src/utils/history.ts
src/utils/log.ts
src/utils/logger.ts
src/utils/looper.ts
src/utils/process-server-status.ts
test/index.test.ts

- Add timestamp each log line
- Ability to Logging in different format for development and production, therefore it becomes easier to read by humans as well as machines.
- Spy on Pino log function
- Improve log messages for alerts, probes, and notifications
This PR wraps log in a function, and change log using [Pino](https://github.com/pinojs/pino).

Refactor: Use Pino for Logging

---

.github/workflows/npm-publish.yml
package-lock.json

ci: make sure the released version can be run before publishing

---

src/index.ts
src/utils/looper.ts
src/utils/process-server-status.ts
test/index.test.ts

- adds --verbose flag
- implements compact logging message format

chore: add --verbose flag and improve log messages

---

src/components/http-probe/index.ts
src/utils/looper.ts

1. Separation of concern (easier development, testability, maintainability)
2. Future possibility to separate things into independent services. 
3. In attempt to fix Issue #26 
Move doProbe function to component directory

Refactor: Separate HTTP probe into component

---

docs/src/pages/overview.md

This change only remove section with empty content. We can easily add once the content is ready

remove empty content on overview

---

src/components/notification/checker.ts

fix: SMTP has no body when send start up message

---

docs/src/pages/guides/notifications.md
docs/src/pages/index.js
src/components/notification/channel/telegram.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/interfaces/data.ts
src/utils/validate-config.ts
test/components/notification.test.ts

feat: adds telegram notification

---

CHANGELOG.md
package.json

This PR updated the change log for 1.3.0 release.

Changelog 1.3.0

---

.vscode/launch.json
package-lock.json
package.json
src/components/config/index.ts
src/components/config/parse.ts
src/components/config/validate.ts
src/components/reporter/index.ts
src/index.ts
src/interfaces/config.ts
src/utils/parse-config.ts

implements issue #117 
Note:
- I added getConfig() function because later the configuration can be updated on the fly with data from monika-hq
- Setup a mock endpoint for monika-hq with [httptarget](https://github.com/hyperjumptech/httptarget)
```bash
curl --location --request POST 'http://localhost:51423/api/paths' \
--header 'Content-Type: application/json' \
--data-raw '{
"base_path": "monikahq/api/handshake",
"delay_min_ms": 0,
"delay_max_ms": 20,
"return_code": 200,
"return_headers": {
"Content-Type": [
"application/json"
]
},
"return_body": "{\"monika\":{\"id\":\"some_uuid\",\"ip_address\":\"this-instance-ip\"},\"data\":{\"probes\":[{\"requests\":[{\"url\":\"http://localhost:51423/delay/50/100\"}],\"incidentThreshold\":1,\"recoveryThreshold\":1,\"alerts\":[\"status-not-2xx\",\"respon …
```

Fetch configuration from monika-hq

---

config_sample/config.telegram.example.json
docs/src/pages/guides/notifications.md
docs/src/pages/quick-start.md

docs: Update notification docs

---

docs/src/pages/overview.md

Editing for easier read and grammar correction

Copywriting revision for easier read

---

.github/workflows/teams-notify.yml

This PR adds a github action to notify Teams when:
- an issue is opened
- a pull request is opened

Add Github action to notify teams

---

docs/src/components/Footer.js
docs/src/components/Nav.js
docs/src/pages/quick-start.md

docs: add links to monika config generator

---

CHANGELOG.md
package.json

This PR updates the changelog.

update changelog for 1.3.2

---

.github/workflows/docs.yml

With this PR, the [docs](https://hyperjumptech.github.io/monika) will be automatically updated when a new NPM release is created.

Update docs when a new release is created

---

CHANGELOG.md
package-lock.json
package.json

This PR updated the changelog for 1.3.3

updated changelog for 1.3.3

---

.github/workflows/docs.yml
docs/next.config.js

fix: change docs and landing page base path

---

src/components/logger/history.ts
src/components/logger/index.ts
src/components/logger/migrations/20210504091802.sql
src/components/logger/migrations/20210510173100.sql
src/components/probe/index.ts

This PR fixes issue #185 
Added new tables in database:
- probe_requests (renamed from history)
- alerts
- notifications

store alert and notification events to db

---

src/components/config/index.ts
src/components/config/parse.ts
src/components/logger/history.ts
src/components/logger/migrations/20210518173100.sql
src/components/probe/index.ts
src/components/reporter/index.ts
src/index.ts
src/interfaces/config.ts
src/looper.ts
src/utils/hash.ts

This PR completed issue #117
- have a valid API key registered in Symon database
- run Symon server in [this PR](https://github.com/hyperjumptech/symon/pull/185)
- run monika with this config
```json
{
"symon": {
"key": <registered API key in Symon>,
"url": "http://localhost:8080/v1/monika",
"id": "qwerty",
"interval": 5000
},
"notifications": [
{
"id": "unique-id-webhook",
"type": "webhook",
"data": {
"url": "https://httpbin.org/post"
}
}
],
"probes": [
{
"id": "httpbin",
"name": "probe 1",
"requests": [
{
"url": "https://httpbin.org/get",
"method": "GET"
}
],
"alerts": [
"response-time-greater-than-1200-ms"
],
"incidentThreshold": 1,
"recoveryThreshold": 1
}
]
}
```

Send alerts and notifications log to Symon in report flow

---

CHANGELOG.md
package-lock.json
package.json

This PR updated the changelog for 1.3.4

Update changelog for v1.3.4

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.3.5.

update change log for 1.3.5

---

src/looper.ts

1. Remove unneeded loop exit
1. when using the `--id` flag, no probe is run
1. Fix the flag checking

Fix Broken --id loop check

---

docs/src/pages/guides/notifications.md
docs/src/pages/quick-start.md

- Fix broken link on Quick Start
- Improve how-to
- Minor corrections

improved: `how-to` documentation

---

config_sample/config.monika-whatsapp.example.json
docs/src/components/Footer.js
docs/src/components/Nav.js
docs/src/pages/guides/notifications.md
docs/src/pages/index.js
docs/src/pages/quick-start.md

This PR adds information about Monika Whatsapp Notifier to the docs and the landing page.

added: Docs: Monika Whatsapp Notifier information

---

CHANGELOG.md
package-lock.json
package.json

- Docs: Monika Whatsapp Notifier information
- Reload probes on config change
- Facebook workplace integration. [@adeyahya](https://github.com/adeyahya) in [#219](https://github.com/hyperjumptech/monika/pull/219)
- Read configuration from url

Add Changelog for 1.3.7

---

docs/src/pages/installation.md

This PR fixes #216 
By adding Troubleshoot section in Installation page
see the installation page

added: Troubleshoot installation docs

---

.github/workflows/node.js.yml
.github/workflows/npm-publish.yml
package-lock.json
package.json
prod_test/index.test.ts
prod_test/mocha.opts
prod_test/tsconfig.json

This PR added initial tests for testing the production (packed, ready to deploy to npm) built of monika, to make sure the published version runs as expected.

added: tests for the production built

---

src/components/probe/index.ts
src/index.ts

Fix #241 
Add event emitter on receiving response.
add event emitter on probeRes
1. run monika
2. see a log "Response received" when there is a response received

added: Emit event on receiving response

---

config_sample/config.desktop.example.json
docs/src/pages/quick-start.md

This PR fixes #259 
This PR adds a link to the desktop notification quick start example documentation
Run docs site, open localhost:3000/overview and see if there is an option for Desktop Notification quick start example

docs: add desktop notif quickstart

---

src/index.ts

Cleanup the log displays
1. Remove logs from event listener since it doesn't have actual functions yet.
2. Closing [261](https://github.com/hyperjumptech/monika/issues/261)
1. run monika from source (bin/run)

Cleanup log display in comand line (CLI)

---

src/index.ts
src/looper.ts

1.  Monika kind of just hang when an id is input. 
2. Closes #271 
1.  type `monika -i "some-id"`
1. Exit with an error

throw error when bad id

---

docs/src/components/landing-page/SpeakerDeck.js
docs/src/pages/index.js

This PR adds speaker deck on landing page.

added: docs: speaker deck on landing page (issue #187)

---

docs/src/pages/guides/cli-options.md

Issue #234.
- Run `cd docs`
- Run `npm run dev`
- Open `http://localhost:3000/guides/cli-options#prometheus`

Docs: Add Prometheus Metrics Documentation

---

src/components/config/validate.ts
src/components/logger/index.ts
src/components/probe/index.ts
src/interfaces/logs.ts
src/utils/pino.ts

1. This PR fixed #296 
I refactored validate.ts to validate allowed probe request method. I copied the available methods from axios and map it into an array so that the probe request method will be validated with the methods array.
This PR also adds method name in the logs
1. Run monika with any configuration as usual
2. Run monika with one of the request is using OPTIONS method
3. Run monika with one of the request is using HEAD method

Functional Suitability : Add More Methods to Monika

---

test/index.test.ts
test/mocha.opts
test/testConfigs/probes/invalidProbeRequestMethod.json

1. Issue #304 
1.  Add `--bail` option to mocha config so that the tests will fail.
1. `npm run test`

Fix issue #304

---

docs/src/pages/guides/cli-options.md
src/index.ts

1. Update missing docs to include `--force` and impolement 
1.  add flag.force detection to `--flush` handler
2. add force documentation on cli-options.md
1. type: `bin/run --flush` should get Y/n confirmation
2. type: `bin --flush --force` should be flushed without confirmation

Update Documentation with --force

---

package-lock.json
src/components/config/validate.ts
src/components/notification/alert-message.ts
src/components/notification/channel/discord.ts
src/components/notification/channel/slack.ts
src/components/notification/channel/telegram.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/components/notification/sender.ts
src/components/notification/termination.ts
src/interfaces/data.ts
src/interfaces/notification.ts
test/components/notification.test.ts
test/components/notification/checker.discord.test.ts

1. Implements #303
2. This PR fixes #322, #318, and #320

refactor: improves message sent to webhook, slack, and discord

---

src/components/config/validate.ts
src/components/notification/channel/mailgun.ts
src/components/notification/channel/sendgrid.ts
src/components/notification/index.ts
src/components/notification/process-server-status.ts
src/components/notification/sender.ts
src/index.ts
src/interfaces/notification.ts
test/components/notification.test.ts
test/components/notification/checker.discord.test.ts
test/components/notification/checker.mailgun.test.ts
test/components/notification/checker.monika-notif.test.ts
test/components/notification/checker.sengrid.test.ts
test/components/notification/checker.slack.test.ts
test/components/notification/checker.smtp.test.ts
test/components/notification/checker.teams.test.ts
test/components/notification/checker.telegram.test.ts
test/components/notification/checker.webhook.test.ts
test/components/notification/checker.workplace.test.ts

1. update typings for notifications so many type assertions can be removed ([Type assertion weakens type safety](https://medium.com/swlh/why-you-should-avoid-type-assertions-in-typescript-5494e3d04dd)).
2. update signature of sendSendgrid and sendMailgun to be more specific
3. remove unnecessary promise chaining in `sendAlerts` function

refactor: update typings for notifications data and remove unused codes

---

CHANGELOG.md
package-lock.json
package.json

- Added: Alert/Notification messages sent to Sendgrid channel (#324)
- Added: TLS Checker (#315)
- Added: Improve Alert/Notification messages sent to SMTP & mailgun channel (#317)
- Added: Improve Alert/Notification messages sent to channels (#309)
- Feature(config): [295] return after create configuration file (#302)
- feature(config): [297] fix monika json generated (#301)
- Add cli documentations (#298)
- feat: use native notifications and remove node-notifier (#329)
- Functional Suitability : Add More Methods to Monika (#299)
- Feat: Flexible user defined alert trigger (#333)
- Use vercel/pkg to generate single binaries (#338)
- Fix: 228 mailgun vulnerability (#325)
- Fix: do not overwrite existing config (#307)
- Fix issue #304 (#305)
- refactor: simplified send desktop notification …

release: 1.5.0

---

CHANGELOG.md
package-lock.json
package.json

Upload Binary Files when New Release (#345 )

Release 1.5.1

---

package-lock.json
package.json
src/components/notification/alert-message.ts
src/components/notification/channel/teams.ts
src/index.ts

1. fixed issue #355 
Before
After

Changed: alert notification message wording

---

src/components/reporter/index.ts

This resolves #364 
1. add `projectID` and `organizationID` keys to symon config
2. add both keys above to request payload to send to symon
1.  Change symon config structure
2. Transform request payload with added `projectID` and `organizationID`
1. Create symon config
```
"symon": {
"id": "monika",
"url": "http://localhost:3000/api",
"key": "your-key",
"projectID": "foo",
"organizationID": "bar"
},
```
2. `npm run start`

symon: add project and organization id

---

src/components/notification/checker.ts
src/components/notification/index.ts
src/index.ts
src/interfaces/notification.ts

1. Fix https://whatsapp.hyperjump.tech notification in [previous PR](https://github.com/hyperjumptech/monika/pull/369).
1.  Provide machine info to start and termination message
1. Use `monika-notif` channel type notification
2. `npm run start`

fix whatsapp.hyperjump.tech notification

---

docs/src/pages/quick-start.md

This PR resolves #406 
1. Fix error on Monika documentation build because of unescaped angle brackets `<>` 
1.  Wrap the filename in backticks
1. `cd docs`
2. `npm run build`

fix docs build

---

docs/src/pages/guides/cli-options.md
src/components/probe/index.ts
src/index.ts
src/looper.ts

1. resolves #415 
1.  added `--keep-verbose-logs` flag
2. change default behavior to store data only when incident or recovery happens
3. If `symon` configuration exists or `--keep-verbose-logs` flag is used, store all data

Changed: Database-less mode

---

CHANGELOG.md
package-lock.json
package.json

This PR to bump version and update changelog

Release 1.6.2

---

CHANGELOG.md
package-lock.json
package.json

This PR is to update changelog and version to 1.6.6

update changelog for 1.6.6

---

src/components/logger/history.ts
src/symon/index.ts

Reported probes are not deleted

fix: reported probes are not deleted

---

CHANGELOG.md
package-lock.json
package.json

This PR is to update change log for 1.6.7

update for 1.6.7 release

---

docs/src/pages/guides/cli-options.md
docs/src/pages/guides/examples.md
docs/src/pages/guides/probes.md
docs/src/pages/guides/tls-checkers.md
docs/src/pages/tutorial/run-in-raspberry-pi.md
docs/src/pages/tutorial/run-with-gmail-notification.md

1. Example and sample consistency
1.  Convert json configs to yaml format

Updating sample configs to yaml

---

src/components/logger/history.ts

1. Wrong number of probes in status notification#512 
1.  Get the number of probes from the config instance.
1. Create a monika.yml with multiple probes and a notification channel, e.g., SMTP.
2. Run ` npm run start -- --status-notification "* * * * *"`
3. Check inbox (if using SMTP) for status notification.
4. The number of probes in the email should be the same with in the configuration file.

fix zero probes in status notification

---

docs/src/pages/guides/alerts.md
docs/src/pages/guides/examples.md
docs/src/pages/guides/probes.md
docs/src/pages/tutorial/run-in-background.md
docs/src/pages/tutorial/run-in-docker.md
docs/src/pages/tutorial/run-with-gmail-notification.md

1. closes issue: #497 
2. closes issue: #522 
1.  Add details and yaml example for alert documentation
2. Replace monika.json examples to monika.yml wherever mentioned

Update documentations for alert notification and old json examples

---

src/index.ts
src/symon/index.test.ts
src/symon/index.ts

1. #527 
1.  add version of the monika in the handshake data
1. Run symon locally
2. Run `npm run start -- --symonUrl http://localhost:3000 --symonKey <insert symon key>`
3. You should see the handshake data printed in the terminal.

add version to handshake data

---

CHANGELOG.md
package-lock.json
package.json

This PR updates Monika to 1.6.8.

Update to 1.6.8

---

docs/src/pages/guides/alerts.md
src/components/tls-checker/index.test.ts

This PR updates documentation about alerts, which will resolve #533 
1.  Added example for Probe and Request Alert
N/A

Docs: Update Request and Probe Alerts

---

CHANGELOG.md
package-lock.json
package.json

This PR updates Monika to 1.6.9

Update changelog for 1.6.9

---

docs/src/pages/tutorial/run-in-background.md
docs/src/pages/tutorial/run-in-docker.md

This PR closes #549 
Updated docs
1. Proofread the updated Markdown files

docs: update running in background

---

docs/src/manifests/manifest.json
docs/src/pages/guides/config.md
docs/src/pages/guides/configuration-file.md
docs/src/pages/guides/notifications.md

1. Closing #555 
2. Add description to monika.yml config file
1.  Add markdown dedicated to monika.yml
2. Add sidebar for Configuration File

Add config file yaml description

---

docs/src/pages/guides/cli-options.md
src/components/config/__tests__/create-config.test.ts
src/components/config/__tests__/expected.insomnia.yml
src/components/config/__tests__/petstore.insomnia.yaml
src/components/config/index.ts
src/components/config/parse-insomnia.ts
src/components/config/parse.ts
src/index.ts

This PR resolves #556
1. Added: Insomnia collection exported file support in JSON & YAML format
2. Limit export format in form of v4
1. Added new flag `--insomnia/-I`
2. Added new file `src/components/config/parse-insomnia.ts`
3. Added new test to `src/components/config/__tests__/create-config.test.ts`
4. Added sample export file `src/components/config/__tests__/petstore.insomnia.yaml`
5. Added expected generated file `src/components/config/__tests__/expected.insomnia.yml`
1. Run from sample file: `npm run start -- --verbose --insomnia src/components/config/__tests__/petstore.insomnia.yaml`
2. Verify probe config
3. Run the test: `npm run test`

added: insomnia support

---

CHANGELOG.md
package-lock.json
package.json

update version and changelog

---

.github/workflows/upload-binary.yml

This PR closes #567 
It seems the author changed his username to vimtor, so I change it to vimtor instead of papiloto
Try create a followup release for this

fix: broken github actions for zipping binaries

---

CHANGELOG.md
package-lock.json
package.json

This PR updates changelog for new release 1.6.11

update changelog for 1.6.11

---

.gitignore
Dockerfile.flyio
docs/src/manifests/manifest.json
docs/src/pages/deployment/deploy-to-fly-io.md
fly.toml.example

This PR fixes #582 
Added docs to deploy to Fly.io
1. `cd /docs` and run `npm run dev`
2. Navigate to `localhost:3000`
3. Open up the Deploy to Fly.io section

Docs: Deploy to Fly.io

---

src/components/config/parse-postman.ts
src/components/notification/__tests__/process-server-status.test.ts
src/components/notification/process-server-status.ts
src/index.ts
src/interfaces/request.ts

fix: not send recovery status when running on Symon mode

---

docs/src/pages/index.js

1. Send CTA events
1.  Send event using GA event function
1. Run `cd docs`
2. Run `npm run dev`
3. Click `Get Started in 30 seconds` button
4. Click `Start now` button
5. Check Google Analytics dashboard

docs: send cta click events to google analytics

---

docs/src/pages/index.js

1. Fix get started copy layout
1.  By enlarge container width
1. Run `cd docs`
2. Run `npm run dev`

docs: fix get started copy layout

---

.github/workflows/upload-binary.yml

1. Fix issue #585 
1.  change the hardcoded version to get from variable
1. Release new version

Fix hardcoded version number in Upload Binary yml

---

CHANGELOG.md
package-lock.json
package.json

This PR updated the changelog for 1.7.1

update changelog for release

---

CHANGELOG.md

This PR updates the changelog for 1.7.1

update changelog for 1.7.1

---

.github/workflows/upload-binary.yml

This PR fixes the empty archive created in upload binary pipeline

fix empty archive after pipeline upload binary

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.7.2

update changelog for 1.7.2

---

.vscode/launch.json
src/components/notification/channel/discord.ts
src/components/notification/index.ts

1. Add text `New Recovery event from Monika` or `New Incident event from Monika` on discord message
1.  Add parameter to function
2. Add some text on message body

bugfix: Discord notification message

---

CHANGELOG.md
package-lock.json
package.json

This PR updates changelog for 1.7.3

Bump version and update changelog

---

docs/src/pages/guides/notifications.md
monika.example.yml
src/components/config/validate.ts
src/components/notification/channel/opsgenie.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/components/notification/validator.ts
src/interfaces/data.ts
src/interfaces/notification.ts

1. This PR add feature [#554](https://github.com/hyperjumptech/monika/issues/554)
1.  Add Opsgenie alert API integration
1.  Dashboard showing `start`, `incident`, `recovery`, and `status-update`
2. Start
3. Incident
4. Recovery
5. Status Update description
6. Docs

Feat-554/opsgenie-integration

---

src/looper/index.ts
src/symon/index.ts

1. This PR fixes [#611](https://github.com/hyperjumptech/monika/issues/611)
1.  Change implemented `clear interval` become `pause interval`

fixing probes interval

---

.github/workflows/docs.yml

This PR fixes failed docs build pipeline

fix docs build pipeline

---

docs/src/pages/index.js

Convey the message that Monika is *very* easy to install.
Change from npm/yarn method to binary packaging.

docs landing page: promote binary install

---

docs/src/pages/guides/cli-options.md
docs/src/pages/quick-start.md

1. Implements #712 
1.  Add missing documentation in the cli-options and the quick-start sections

Doc: Add Missing Documentation

---

docs/src/components/SidebarMobile.js

1.  Search Algolia error on mobile view
1.  change component search to searchbox

[722/refactor]: Search Algolia error on mobile view

---

Dockerfile
docs/src/pages/tutorial/run-in-docker.md

1. Updated the Dockerfile
2. Updated documentation
1. Dockerfile was using outdated /config/monika.JSON
2. Removed the `-c config/monika.json` parameter from the CMD line. Monika without parameter will pull a config and will work better as a minimal config out of the box. Also we assumed that user will know to copy the file to /config first.
3. Added the `--net` param to allow stun checking to work correctly in a container
1. Create an image from the current Dockerfile : `docker build -f Dockerfile . -t <your_image_name>`.
2. Run the container with the `docker run --name monika-local --net=host -it <your_image_name>`. 
3. Docker should run with stun checking working.

update dockerfile and docs

---

docs/src/pages/guides/alerts.md
docs/src/pages/guides/cli-options.md
docs/src/pages/guides/configuration-file.md
docs/src/pages/guides/examples.md
docs/src/pages/guides/probes.md
docs/src/pages/guides/status-notification.md
docs/src/pages/guides/troubleshoot.md

No ticket but found some errors in our docs
1. Fixed spelling errors
2. Fixed grammar
3. Clarify some descriptions

Docs: Fix documentations erros

---

docs/src/pages/guides/examples.md

1. Build error fix
1.  Changed line 16 to update cache
Build on local is successful

Fix docs build error 

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.8.1

update changelog for 1.8.1

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the change log for 1.8.2

update changelog for 1.8.2

---

CHANGELOG.md
package-lock.json
package.json

This PR updates change log for 1.9.0

update to 1.9.0

---

docs/src/pages/index.js

1.  [745/docs]: broken landing page when navigating from docs
1.  
1. Go to https://monika.hyperjump.tech/overview
2. Click on Monika logo
3. Scroll down to the integrations list.
https://user-images.githubusercontent.com/47026826/177137663-85fbdf17-3cec-44ca-86ff-8af593dec726.mov

[745/docs]: broken landing page when navigating from docs

---

docs/src/pages/guides/alerts.md
docs/src/pages/tutorial/run-in-raspberry-pi.md

Docs: Wrong tags in Alert and Raspberry pi pages #753
Go to https://monika.hyperjump.tech/guides/alerts or https://monika.hyperjump.tech/tutorial/run-in-raspberry-pi

Docs: Wrong tags in Alert and Raspberry pi pages (#753)

---

docs/src/pages/guides/new-notifications.md

Docs: Redundant title in New Notifications page(#754)
Go to https://monika.hyperjump.tech/guides/new-notifications#introduction

Docs: Redundant title in New Notifications page(#754)

---

docs/src/pages/guides/examples.md
docs/src/pages/guides/notifications.md
docs/src/pages/guides/probes.md

1. Found issues in notification channel examples
1.  Fixed and cleaned up the notification examples, found some copy paste errors
2. Update Probes.md text, mentioning all the different requests.
3. Some grammar updates.

Improve documentation details

---

docs/public/playground_assets/copy.svg
docs/src/components/Highlight2.js
docs/src/components/NavIndex.js

1.  Feature copy code to clipboard (#769 )
1.  Add button with copy function

Copy code to clipboard

---

docs/src/pages/guides/alerts.md
docs/src/pages/guides/configuration-file.md
docs/src/pages/guides/examples.md
docs/src/pages/guides/probes.md
docs/src/pages/tutorial/run-with-gmail-notification.md

1. Resolve #808 
1.  Add comments on all interval, timeout, and response time in all examples.

Docs: add comments on all interval, timeout, and response time (#808)

---

docs/src/pages/overview.md

1. Resolve #812 
1.  Add list of features in the overview page
1. `cd docs && npm run dev`

Update overview with list of features

---

docs/src/components/LayoutDocs.js
docs/src/components/NavBar.js

1. Docs: TOC obscured by header when scrolling down (#788)
1.  
1. cd docs
2. npm run dev

Docs: TOC obscured by header when scrolling down (#788)

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.10.0 release

Update changelog for 1.10.0

---

monika-config-schema.json
test/json-schema/validate-sample-configs.test.ts

1. Closing #794 
2. Closing #795 
3. Closing #804 
1.  Adding titles to notification objects for better dispaly when suggested
2. Add defaults for url and alerts to help autosuggestion
3. EDIT **Added fix for timeout default**
1. Please see PR #816 on how to test.
https://user-images.githubusercontent.com/964106/180918264-48177618-9002-4e1b-9a72-a1f8ac7c18e1.mp4

Improve notification suggestion titles, Add probe suggestions

---

monika-config-schema.json
test/json-schema/validate-sample-configs.test.ts

1. Closing #798 
1.  Add schema properties for certificate
1. Use this latest json schema for testing, On VSCode goto File --> Preferences, type "schema" above and you should see:
2. Under the **settings.json** we can define a specific schema (this updated schema file) to a test file type say `test.yaml`:
(your original yaml setting will not be affected/modified)
3. You might need to quit vscode and start it again for the settings to be updated.
4. Next open up VSCode and open/create a config file `test.yaml`:
```yaml
certificate:
domains:
- https://hello.com
- domain: http://example.com
options:
path: /foo
- example.com
```
1. Should show details and description on mouse over
2. Should validate for url http/https prefix for domain
3. Should allow for domain object and remainder (as …

Add certificate validation

---

.github/workflows/auto-pr-schemastore.yml

1. Closing #744 
2. Add auto PR workflow 
Created a new workflow
1. Check out the schemastore repo 
2. Get the latest schema from monika repository to update it
3. Use Github Action pete-evans/create-pull-request to create new PR to schemastore
1. Please help create token "AUTO-PR-TOKEN" scoped to "repo" 
It works (given the proper token)

Add auto pr workflow

---

.github/workflows/auto-pr-schemastore.yml

1. Fix schemastore repo typo
1.  schemastore/schemastore.git ==> Schemastore/schemastore
successful pull

Update repo name

---

.github/workflows/auto-pr-schemastore.yml

This PR fixes the workflow to create PR to schema store

fix auto PR to schema store workflow

---

.github/workflows/auto-pr-schemastore.yml

1. Improve auto pr message
1. Remove message about auto pr, not needed
2. Add sync step to our fork 
3. Made the message more generic

Improve auto pr commit workflow

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.11.0

Update changelog for 1.11.0

---

docs/src/pages/guides/examples.md

1. resolves #849 
1.  Fix the example.
1. cd docs && npm run dev

Docs: fix request chaining example

---

src/components/config/__tests__/create-config.test.ts
src/components/config/index.ts

1. Fix repeatability in testing
2. Could not run test repeatedly due to user overwrite prompt
1. Delete the file before running test
1. run `npm run test`
2. run `npm run test` again
4. Running test multiple times should work 
Before PR

[Test] Fix test timeout/repeatability 

---

docs/src/pages/guides/cli-options.md

1. Grammar/Typo on cli options
2. 
1.  Fixed to
"The '--summary' flag also will not work when no other monika process is running."
1. go to the /doc directory of the repository
2. `npm ci`
3. `npm run dev`

Fix minor grammar/typo

---

src/components/logger/request-log.ts
src/context/index.ts
src/index.ts

1. 779/refactor: Request in verbose mode
1. bin/run --verbose
send request:

779/refactor: Request and response in verbose mode

---

src/looper/index.ts
src/symon/index.ts

improve: pause probing when cannot report to Symon

---

src/components/probe/index.ts
src/looper/index.ts
tsconfig.json

Monika doesn't save requests to local db and can't send report to Symon

---

CHANGELOG.md
package-lock.json
package.json

This PR updates the changelog for 1.12.1

Update changelog for 1.12.1

---

.github/workflows/docs.yml

1. error workflow docs/jq
1.  
1.

fix: update workflow jq

---

CHANGELOG.md
package-lock.json
package.json

- Added: Import from simple Text File
- Added: Docs from Medium blog posts
- Added: Push docker Image any version
- Fixed: edit search UI
- Fixed: reduce complexity
- Fixed: Change repository name on Docker Publish from Tag github workflow
- Fixed: update workflow jq
- Fixed: deprecationHandler and sanitizeProbe alert bugs

Release 1.13.2

---

.github/workflows/docs.yml

fixed: rename api key algolia
rename api key algolia

Fixed: update workflow docs

---

test/others/fakes.test.ts

1. Closing #902 
2. Test was intermittently failing
1.  Removed millisecond from Date String comparison.
1. `npm run test` should pass consistently now
(running test/others/fakes.test.ts only)

Update fakes.test.ts to pass consistently

---

src/components/config/__tests__/create-config.test.ts

1. Fix test repeateability
1.  Add force flag when creating config from text file
1. use `npm run test`
2. run `npm run test` again
3. Test should be successful both times and any subsequent tests again

Improve Test Repeatability

---

docs/algolia.json

1. can't search in detail
1.  update json
1. cd /docs
2. npm run dev

fixed: update json algolia

---

.github/workflows/sonar-cloud.yml
sonar-project.properties

1. Implements #901 
1.  Add sonar-cloud.yaml in the github workflow
1. Trigger the workflow manually
2. Goto Actions, click on the Sonar Cloud Workflow

Add sonar-cloud workflow

---

sonar-project.properties

1. Fix small typo on test path
2. Add wildcard patterns for tests within src

Add test paths to SonarCloud parameters

---

sonar-project.properties

1. Reverting project name to "Monika-Synthetic Monitoring"
2. Add differentiation on the dashboard (already a few "monika" projects)  
Current Name on Dashboad:
Saat di search:

Update sonar cloud project name

---

docs/src/pages/guides/notifications.md
src/components/config/validate.ts
src/components/notification/channel/gotify.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/components/notification/validator.ts
src/interfaces/data.ts
src/interfaces/notification.ts
src/monika-config-schema.json

1. added new Notification type for Gotify (https://gotify.net)
1.  Followed docs for new notification and adapted Pushover, which has similar mechnics
1. Install a Gotify server: https://gotify.net/docs/install
2. Create application token inside Gotify
3. Configure notification type according to guides/notifications#gotify
4. See notifications in Gotify web interface and configured clients

New Notification: Gotify

---

.eslintrc
src/components/notification/channel/dingtalk.ts
src/components/notification/channel/gotify.ts
src/components/notification/channel/opsgenie.ts
src/components/notification/channel/pushover.ts
src/components/notification/channel/telegram.ts
src/components/notification/channel/webhook.ts
src/components/notification/channel/workplace.ts

1. As a part of the effort to solve issue #679.Enable [no-useless-catch](https://eslint.org/docs/latest/rules/no-useless-catch) ESLint rule
1.  Enable the rule
2. Fix violated code
1. Run `npm run posttest`

ci: enable no-useless-catch rule

---

docs/src/pages/guides/probes.md
package-lock.json
package.json
src/components/config/validate.ts
src/components/mariadb-request/index.ts
src/components/probe/index.ts
src/interfaces/probe.ts
src/interfaces/request.ts
src/monika-config-schema.json

1. Implement #913
2. Add MariaDB probe
1. Add mariadb library.
2. Update validation / json-schema 
3. Add guide probe documentation
1. run `npm run test` should all pass
2. create something like the  following `test.yaml`:
```yaml
notifications:
- id: unique-id
type: desktop
probes:
- id: 'id-mariadb'
name: Mariadb probe
mariadb:
- host: 172.17.0.1
port: 3306
username: user
password: password
database: mydb
alerts:
message: 'Alert! DB offline'
- id: 'id mysql'
name: Mysql Probe
mysql:
- host: 172.17.0.1
port: 3306
username: user
password: password
database: mydb
alerts:
message: 'Alert! DB offline'
```
3. run `bin/run-dev -c test.yaml …

add mariadb probe

---

CHANGELOG.md
package-lock.json
package.json

This PR updates changelog and version for 1.14.0

update changelog and version for 1.14.0

---

.github/workflows/auto-pr-schemastore.yml

1. Tweak autopr workflow to pass test
1.  Commit update first before calling test

commit changes before test

---

.github/workflows/auto-pr-schemastore.yml

1. Missing authorship when committing
1.  Add explicitly author into the git config
(note: no changes in file )

Declare explicit author in autopr workflow

---

.eslintrc
src/components/config/parse-insomnia.ts
src/components/logger/history.ts
src/components/notification/channel/discord.ts
src/components/notification/channel/googlechat.ts
src/components/notification/channel/lark.ts
src/components/notification/channel/pagerduty.test.ts
src/components/notification/channel/slack.ts
src/components/notification/channel/teams.ts
src/components/notification/index.ts
src/components/notification/validator.ts
src/components/probe/index.ts
src/interfaces/config.ts
src/interfaces/data.ts
src/interfaces/whatsapp.ts
src/jobs/tls-check.ts
src/plugins/validate-response/__tests__/index.test.ts
src/plugins/validate-response/checkers/__tests__/index.test.ts
src/plugins/visualization/atlassian-status-page/database.ts
test/components/notification/checker.pushbullet.test.ts
test/components/notification/checker.smtp.test.ts

1. As a part of the effort to solve issue #679.
Enable the following rules and fix the violated codes
- unicorn/no-array-callback-reference
- camelcase
- unicorn/consistent-function-scoping
- unicorn/prefer-string-slice
1. Run `npm run posttest`

CI: Enable Some ESLint Rules

---

CHANGELOG.md
package-lock.json
package.json

This PR update the changelog for 1.14.1 release.

Update changelog for 1.14.1

---

src/components/config/__tests__/create-config.test.ts
src/components/config/create-config.ts
src/components/config/index.ts
src/components/config/parse-sitemap.ts
src/components/config/parse-text.ts
src/components/config/parse.ts
src/components/http-request/http-request.test.ts
src/components/http-request/index.ts
src/context/index.ts
src/context/monika-flags.ts
src/index.ts
src/loaders/index.ts

1. Add Monika flags type
1. Create the Monika flags type
2. Change all the parameter of the Monika flags type
3. Move the Monika flags default value into one file 
1. Run Monika as usual

Chore: Add Monika Flags Type

---

.eslintrc
src/components/logger/history.ts

Add type for history log data from database
Replace `any` type with the proper type
1. Run `npm run -- --logs`
2. Run Monika in the Symon mode until it sends report to Symon
3. Run `npm run posttest`

Chore: Improve History Log Type

---

package.json

Although seemingly small, even minor changes can have a significant impact, much like the [butterfly effect](https://en.wikipedia.org/wiki/Butterfly_effect) (although not in the context of chaos theory)

chore: improves `package.json` keywords

---

package-lock.json
package.json
src/components/logger/startup-message.test.ts
src/components/logger/startup-message.ts
src/index.ts

1. As a part of an effort to reduce complexity. Issue #989.
1.  Add tests
2.  Separate the function
3. Enable a disabled linter rule
4. Upgrade Typescript version
1. Run `npm test`
2. Run Monika as usual

Refactor: Reduce Startup Message Function Complexity

---

src/components/config/validation/notification-required-fields.ts

1. 
1.  add validate 
1. add statuspage notification in monika.yml
2. run npm start

fix: create validate statuspage

---

.github/workflows/auto-pr-schemastore.yml

1. Implements #1004 
2. Fixes broken pr submission workflow
1.  The testing "Make file" dissappeared
2. Using `npm run build` instead to test schema before submission

update schema testing workflow

---

docs/src/pages/guides/new-notifications.md

1. Implements #999 
1.  Add mention of json schema when adding new notification
2. Gave schema example

Add mention of json schema in documentations

---

docs/src/pages/tutorial/deploy-to-fly-io.md

This PR fixes #1023 
Updated the documentation to deploy Monika using Fly.io
1. Read the docs (thanks, Captain Obvious)

Docs: Update Deploy to Fly.io documentation

---

package-lock.json
package.json
src/components/config/parse-insomnia.ts
src/components/probe/prober/http/request.ts
src/interfaces/request.ts

This PR closes #1027 
It is explained in this [issue](https://github.com/vercel/pkg/issues/1822) that `axios@1` breaks the PKG build.
This PR downgrades the Axios to 0.27.2 (The most recent `axios@0` version) and some adjustments 
1. Build the Monika app using `npm run prepack && pkg . --compress brotli -t node16-linux-x64`  to build in Linux environment. Change the `node16-linux-x64` to your platform (which you can refer to [here](https://github.com/vercel/pkg#targets)
2. Run the built binary
2a. Use Monika as usual
Logs are provided below:
1. With `axios@1.3.4`
<details>
<summary>Expand logs</summary>
```bash
❯ npm run prepack && pkg . --compress brotli -t node16-linux-x64
> @hyperjumptech/monika@1.15.1 prepack
> npm run clean && tsc -b && oclif manifest
> @hyperjumptech/monika@1.15.1 …
```

Fix: Downgrade Axios to be able to build binary using PKG

---

.github/workflows/auto-pr-schemastore.yml
.github/workflows/nightly-release.yml
.github/workflows/npm-publish.yml
.github/workflows/publish-snap.yml
.github/workflows/upload-binary.yml

1. Update workflows
2. Notification was exported, need a small step to build it
1.  Adding `npm run build -w  packages/notification`

Update workflows to build notifications

---

src/components/config/get.ts
src/components/config/index.ts

Fix Monika doesn't probing when config changes with an empty probe interval 
Reuse function to get config on the file watcher
1. Run Monika
2. Change the config
https://github.com/hyperjumptech/monika/assets/15191978/93ffb824-1e25-4e25-b231-961b5e5be3cc
https://github.com/hyperjumptech/monika/assets/15191978/0bef7c7f-f244-4743-81e6-51ac531757aa

Fix: Probe Doesn't Run After Change Config

---

src/components/probe/index.ts
src/looper/index.ts
src/utils/probe-state.test.ts
src/utils/probe-state.ts

Fix undefined probe. This will resolves #1066.
test: add probe state test
refactor: extract getLastStart function
refactor: extract getLastFinish function
test: add test for probe id not found
fix: crashes when config changes
refactor: change some types
fix: handle probe context can be undefined
fix: handle getProbeState can be undefined
refactor: slide setProbeRunning statement into setTimeout callback
fix: handle setProbeRunning can be failed
refactor: slide setProbeRunning and getRandomTimeoutMs statements
1. Run the following config until the probe is running
```yaml
probes:
- id: "Google"
requests:
- url: https://google.com
- id: "YouTube"
requests:
- url: https://youtube.com
- id: "Facebook"
requests:
- url: https://facebook.com
- id: "Twiter"
requests:
- url: https://twitter.com
- …
```

Fix: crashes when some of the probe is removed from the configuration

---

.github/workflows/nightly-release.yml

1.  Force PR token to "read" only
1.  Add write permission for PRs

Fix broken Nightly Workflow

---

.github/workflows/docs.yml

1. Fail pushing to github docs
2. Add write permission on push to docs workflow

Fix permision for docs deployment 

---

.github/workflows/publish-snap.yml
package.json

Fix broken publish snapcraft pipeline
1. Add install and build workspaces
2. Change notification workspace package path before pack the tarball
1. Install workspaces dependencies. Run `npm ci --workspaces --if-present`
2. Build workspaces. Run `npm run build --workspaces --if-present`
3. Install Monika directory. Run `npm ci`
4. Change monika notification package path. Run `sed -i 's#packages/notification/hyperjumptech-monika-notification#../../packages/notification/hyperjumptech-monika-notification#g' package.json`
5. Pack the tarball. Run `npm run pack-tarballs`

Fixed: Broken Publish Snapcraft Pipeline

---

.github/workflows/docs-build.yml

1. fix `ERESOLVE could not resolve` build error

Fix doc build workflow

---

CHANGELOG.md
package-lock.json
package.json
packages/notification/package.json

1. Prepare for Release v1.15.6
- Undefined Notification Message (#1103)
- Webhook Notification is Not Working (#1102)
- Make Probe Requests Property Optional (#1096)
- Make HTTP Prober a Subclass (#1107)
- Test the Packages Directory (#1106)
- Update chaining request docs (#1101)
- Improve Disconnect Notification (#1095)
- Add simple success/fail result to each probe and new prometheus metric (#1061)

Update for Release v1.15.6

---

CHANGELOG.md
package-lock.json
package.json
packages/notification/package.json

1. Update for release v1.15.7
- Remove change empty array fallback for requests (#1113)
- Mailgun notification handle node 18 (#1105)
- Make the Probe Result a Mandatory Type (#1111)
- Remove node_options environment variable when running test (#1112)
- Adding sendWithCustomContent in sendgrid (#1109)

Update for release v1.15.7

---

.github/workflows/package-notification-publish.yml
package-lock.json
package.json

1. cannot install monika via npm
1. change package.json so that monika-notificaiton is installed from npm
1. npm i
2. npm run test
3. npm run start

fix: monika install

---

src/context/monika-flags.ts
src/index.ts
src/symon/index.test.ts
src/symon/index.ts

1. Add a new flag `--symon-api-version` to use the Symon API version.
1. Add `--symon-api-version` when running Monika with Symon mode.

Feat: adds a new flag to use the Symon API version

---

src/components/logger/flush.test.ts
src/flag.ts
src/symon/index.ts

Fix fail to connect to Symon.
Assign `SYMON_API_VERSION` enum to a string value.
Connect Monika to Symon

Fix: Fail to Connect to Symon

---

CHANGELOG.md
package-lock.json
package.json
packages/notification/package.json

Update change log and update version to 1.15.10.

Release: Update Change Log and Update Version to 1.15.10

---

src/components/probe/index.ts

This is a hotfix to reduce Monika load.
Increase initial delay when retrying a probe.
1. Run Monika
2. Stop the target
3. Run the target
https://github.com/hyperjumptech/monika/assets/15191978/113fd08a-fa75-44e3-a6a6-199d69905fc5

Feat: Add Initial Delay

---

.github/workflows/docker-release-from-tag.yml

This PR fixes #1148
Added npm run build -w notification package
N/A

Fix: Docker Release from tag pipeline

---

CHANGELOG.md
package-lock.json
package.json
packages/notification/package.json

Update change log and update version to 1.15.11.

Release: Update Change Log and Update Version to 1.15.11

---

package.json
src/symon/index.ts

This PR fixes #1166 (Hopefully)
1. Define the path for the worker correctly
1. Start Monika using npm pointing to local Symon
2. `npm pack`, install the pack, start Monika using npm pointing to local Symon
3. `docker build . -t monika`, run dockerized Monika using npm pointing to host Symon

Fix: [SymonClient] Report worker path

---

packages/notification/package.json

Upgrade monika-notification package version to 1.15.12

Release: Upgrade monika-notification Package Version to 1.15.12

---

src/components/probe/prober/http/request.ts

This PR is an additional fixed for #1181
1. Add EPROTO and EHOSTUNREACH error handler
2. If there is any unhandled error, give them the context about the error stack
1. Trigger EPROTO and EHOSTUNREACH error
This PR has no videos/test, but will surely fixes these problems:

Fix: Add EHOSTUNREACH and EPROTO error handler

---

.github/workflows/npm-notification-publish.yml
packages/notification/README.md

1. Last fix didn't properly trigger workflow #1192
2. Path was wrong
1. Path "packages/" missing an "s"
Co-authored-by: @raosan

Fix path typo

---

CHANGELOG.md
package-lock.json
package.json

Release version 1.16.1
1. Update changelog
2. Update the version and run `npm run install`

Release: Version 1.16.1

---

packages/notification/package.json

Bump monika-notification package to 1.15.13

Release: Bump monika-notification package to 1.15.13

---

CHANGELOG.md
package-lock.json
package.json

Release Monika version 1.16.2.
1. Update change log.
2. Update the application version.
3. Update the package lock file.

Release: Version 1.16.2

---

package-lock.json
package.json
src/components/logger/history.ts
src/looper/index.ts
src/symon/index.ts
src/utils/probe-state.ts

Update probe in Symon mode without restarting. It will resolve #1163.
1. Always get the latest probe data from the cache for each iteration.
2. Update the local probe state when there are probe data changes.
1. Run Monika in Symon mode.
2. Add, update, and delete a probe.
3. Run Monika in Monika mode.
https://github.com/hyperjumptech/monika/assets/15191978/a50e16cf-cd04-4905-9ec0-30df57c040bd
https://github.com/hyperjumptech/monika/assets/15191978/ab0e5a39-acbf-4c0e-b168-605b36c338a9

Refactor: Update Probe in Symon Mode Without Restarting

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.16.3

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.16.4

---

packages/notification/package.json

Bump notification package minor version since #1215 had breaking changes on `util/authorization.ts`
1. Bump notifcation package

Chore: Bump notification package to v1.16.0

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.17.0

---

CHANGELOG.md
package-lock.json
package.json

Release:  Version 1.19.1

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.19.2

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.20.0

---

docs/src/pages/guides/tls-checkers.md

Remove probes property from TLS checker config example.

Docs: Remove probes property from TLS checker config example

---

CHANGELOG.md
package-lock.json
package.json
packages/notification/utils/authorization.ts
src/components/incident/index.ts
src/components/probe/prober/http/request.test.ts
src/plugins/metrics/prometheus/collector.test.ts
src/plugins/metrics/prometheus/collector.ts
src/utils/http.ts

Release: Version 1.20.1

---

src/components/probe/prober/http/request.ts

This PR fixes #1308 
1. Add handler for ERR_TLS_CERT_ALTNAME_INVALID
2. Improve error message to include possible solution.
Trigger an error

Feat: Handle ERR_TLS_CERT_ALTNAME_INVALID and improve overall error descriptions

---

CHANGELOG.md
package-lock.json
package.json

Release: Version 1.21.0

---

CHANGELOG.md
package-lock.json
package.json

Feat: Add --sentryDSN flag (#1325)
Fix: --ignoreInvalidTLS flag has no effect (#1331)

Release 1.21.2

---

packages/notification/package.json

Upgrade the notification package version to fix the [failed pipeline](https://github.com/hyperjumptech/monika/actions/runs/13067809237/job/36463066141).

Fix: Upgrade Notification Package Version
