hyperjumptech/monika

docs/src/pages/guides/probes.md
src/utils/looper.ts

I found the display of all the probes in the config while repeating annoying.
So displaying the probes once, and only the results during looper.
1. removed the probe display/logs from main loop
2. fix some typos

fix: update display while looping

---

docs/src/pages/quick-start.md

This PR fixes incorrect links (probes, alerts, notifications) in quick start docs.

docs: fixes incorrect links in quick start docs

---

docs/src/components/Seo.js

This PR fixes the links inside the `head` tag for 
- open graph image
- twitter image
- favicons
To view production build locally:
- `cd docs`
- `npm install`
- `npm run build`
- `mv out out.bak && mkdir out && mv out.bak out/monika`
- `npx serve out`
- Open browser and go to http://localhost:5000/monika

fix links to social media images and favicons

---

bin/run

This PR replaces `http-probe` strings to `monika` in the exit message.

Update exit message

---

docs/src/components/Seo.js

This PR fixes the content `og:image` and `twitter:image` to use the correct URL. It was mistakenly pointing to `https://github.com/hyperjumptech`. It should have been `https://hyperjumptech.github.io`.

fix social media preview images links

---

config.example.json
test/testConfigs/mailgun/mailgunconfig.json
test/testConfigs/noInterval.json
test/testConfigs/probes/invalidProbeRequestAlert.json
test/testConfigs/probes/invalidProbeRequestMethod.json
test/testConfigs/probes/invalidProbeRequestURL.json
test/testConfigs/probes/noProbeAlerts.json
test/testConfigs/probes/noProbeName.json
test/testConfigs/probes/noProbeRequest.json
test/testConfigs/probes/noProbes.json
test/testConfigs/sendgrid/sendgridconfig.json
test/testConfigs/smtp/smtpconfig.json
test/testConfigs/smtp/smtpconfigNoRecipients.json
test/testConfigs/webhook/webhookconfig.json
test/testMail/smtp.test.ts
test/utils/is-valid-url.test.ts

example.com domain is intended for documentation and also described in [RFC 2606](https://tools.ietf.org/html/rfc2606) and [RFC 6761](https://tools.ietf.org/html/rfc6761). It makes user understand that the domain is only example, and it prevents accidentally get email or traffic from Monika.

Chore: Change example, test, and documentation domain to example.com

---

src/utils/parse-config.ts

Change url of example config file when there is no config file

chore: Change the link to download config sample from github

---

docs/src/pages/guides/notifications.md

This PR attempts to improve the documentation on SMTP Notification:
- Move the SMTP Notification to the top since it's the easiest to set up.
- Add example to use Gmail SMTP server.

docs: update SMTP docs

---

src/utils/looper.ts
src/utils/validate-config.ts

This PR fixes #59 which is to solve displaying No Threshold warning only once instead of each probing.
Before:
After:

Removed No Threshold Warning from looper.ts

---

src/utils/parse-config.ts

This PR fixes #74 , which is to fix error displayed when JSON configuration file is in invalid format.

Improve Error Logs when Reading JSON Configuration File

---

docs/src/pages/quick-start.md

This PR adds a section in docs on how to run Monika in the background.

docs: add explanation how to run in background

---

.github/workflows/node.js.yml
.github/workflows/npm-publish.yml

implementing issue #96 by adding command in `npm-publish.yml`:
- get package version
- webhook

chore: Notify Hyperjump Teams channel when publish new version

---

README.md

Fixes #103 
Change docs link to https://hyperjumptech.github.io/monika/quick-start
Change links to Probes, Notifications, and Alerts to https://hyperjumptech.github.io/monika

Docs: Fix Broken Link

---

src/utils/validate-config.ts

Fixes #109 :
When I ran Monika without notifications in windowed terminal, and the window width is not full-screen, it will throw an error `RangeError: Invalid count value`
Remove align center
1. Run `npm run test`

Fix: Test Error When Use Smaller Width Console

---

docs/src/siteConfig.js

right now all edit URL is pointing to master branch, since there is no master anymore, so its broken

Fix broken URL to edit on github

---

docs/src/pages/guides/probes.md
package-lock.json
package.json
src/components/http-probe/index.ts
src/interfaces/request.ts
src/utils/history.ts
src/utils/logger.ts
src/utils/probing.ts
src/utils/validate-config.ts
test/index.test.ts
test/testConfigs/probes/chainingRequests.json
test/testConfigs/probes/multipleProbeRequests.json

This PR will hopefully fixed #82 
This PR adds an empty array called responses, which will be used for storing response data every time any probe is doing request. Then, URLs and Headers that has the type `string`, will be compiled using Handlebars.
Handlebars will compile `{{ }}` texts in the config.json file, which allowing request to get data from stored responses.
1. Use this probe configuration:
```json
"probes": [
{
"id": "1",
"name": "Probing Github",
"description": "simulate html form submission",
"interval": 10,
"requests": [{
"method": "GET",
"url": "https://reqres.in/api/users",
"timeout": 7000,
},{
"method": "GET",
"url": "https://reqres.in/api/users/{{ responses.[0].data.data.[0].id }}",
"timeout": 7000,
}],
"incidentThreshold": 3,
"recoveryThreshold": 3,
"alerts": …
```

Ability to Use Previous Request(s) Response in Chaining Requests

---

README.md
config_sample/config.teams.example.json
docs/src/pages/guides/notifications.md
src/components/http-probe/index.ts
src/components/notification/channel/teams.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/interfaces/data.ts
src/interfaces/notification.ts
src/utils/validate-config.ts
test/index.test.ts
test/testConfigs/teams/teamsconfig.json
test/testConfigs/teams/teamsconfigNoURL.json

This PR fixes #115 which is to implement Microsoft Teams notifications
I added a notification system for using Microsoft Teams by creating an empty teams with one channel, added a Connector called Incoming Webhook to the channel, saved the Webhook URL generated from the connector, and lastly push a request to the Webhook URL.
1. Refer to this guide on how to getting the Webhook URL: [https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
2. Copy the `config.teams.example.json` from `config_sample/`
3. Change the YOUR_TEAMS_WEBHOOK_URL to your Teams Webhook URL
4. Run monika with your desired URL to probe and alerts
Below are the …

Enable Sending Notifications via Microsoft Teams

---

Dockerfile

This PR fixes issue #123 
The issue happened because docker publish and npm publish run around the same time, so the version of monika from npm got at the time of building image is still the previous one.
I changed the `npm install -g ...` process to install from source code, not from the npm repository

fix: monika version in docker is not the latest

---

.github/workflows/teams-notify.yml

The Notify Teams workflow will always fail because the secrets to notify Microsoft Teams are not exposed when `pull_request` event is triggered.
Use `pull_request_target` trigger event.

chore: fix notify teams workflow

---

package-lock.json
package.json
src/components/config/index.ts
src/components/logger/history.ts
src/components/logger/index.ts
src/components/logger/migrations/20210504091802.sql
src/components/reporter/index.ts
src/index.ts
src/looper.ts

implementing part of issue no #167
- remove configuration update from report flow
- update report request headers and payload in accordance with what Symon expect
- use [sqlite](https://www.npmjs.com/package/sqlite) library which adds ES6 promises and SQL-based migrations API to [sqlite3](https://www.npmjs.com/package/sqlite3).
**This PR need to be tested against this PR in Symon [https://github.com/hyperjumptech/symon/pull/164](https://github.com/hyperjumptech/symon/pull/164)**
- first, you need to create an API key in Symon database
- run Symon server
- run monika with this configuration
```json
{
"monika-hq": {
"url": "http://localhost:8080/v1/monika",
"id": "<monika instance id>",
"key": "<valid API key>",
"interval": 5000
},
"probes": [
{
"requests": [
{
"url": …
```

Remove configuration renewal from the report flow and update log database

---

src/components/config/validate.ts
src/components/notification/channel/monika-notif.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/components/notification/validator.ts
src/components/probe/index.ts
src/interfaces/data.ts
test/components/notification.test.ts
test/components/notification/checker.monika-notif.test.ts
test/index.test.ts
test/testConfigs/fullConfig.json
test/testConfigs/monika-notif/monikaNotifconfig.json

To get notification via our MonikaNotificationEngine, we need to add a new notification channel called monika-notification. 
By adding the monika-notif channel to send through MonikaNotificationEngine. 
Closes #175 
1. add monika-notif config to monika.json configuration
```script
{
"id": "unique-id-monika",
"type": "monika-notif",
"data": {
"url": "http://localhost:3000/api/notify?token=5179f5f4-5b68-409b-acd6-322939b36045"
}
}
```
2. run `npm start`

(ISSUE 175) Add Monika notification channel

---

package.json

Related with this error: https://github.com/hyperjumptech/monika/runs/2637697050?check_suite_focus=true
The error:
Revert `package.json` configuration. On [previous PR](https://github.com/hyperjumptech/monika/pull/191), there is some changes in `package.json` that I thought is not necessary but unfortunately is needed by CI to push to NPM.

fix: Error: Cannot find module ../lib

---

src/components/logger/history.ts
src/components/logger/index.ts
src/components/probe/index.ts

This PR fixes #199 
When the URL cannot be reached, there is an error.
```
2021-05-25T23:46:36.406Z Error: Can't insert data into monika-log.db. SQLITE_CONSTRAINT: NOT NULL constraint failed: probe_requests.request_method
```
- Change the source of request config data for logging to original config from json file, instead of using config from returned response by axios
- Added default value for data that might be empty

fix: db error when URL is unreachable

---

CHANGELOG.md
package-lock.json
package.json

- Add Monika Whatsapp Notifier documentation (#209)
- Monika now does not save response body to database (#198)
- Improved How-To Documentation (#205)
- Fix Looping by ID when ID is not present (#200)
- DB error when URL is unreachable (#201)
- Failed on sending incident notification to monika notification (#207)

Add Changelog for 1.3.6 Release

---

config_sample/config.workplace.example.json
docs/src/pages/guides/notifications.md
src/components/config/validate.ts
src/components/notification/channel/workplace.ts
src/components/notification/checker.ts
src/components/notification/index.ts
src/components/notification/validator.ts
src/interfaces/data.ts
test/components/notification/checker.workplace.test.ts

Hello everyone, I made this pr so that Monika can send notifications via Facebook Workplace. Please kindly check and review it thanks.

feat(notification): facebook workplace integration

---

src/components/logger/history.ts
src/components/reporter/index.ts
src/looper.ts

This PR fixes issue https://github.com/hyperjumptech/monika/issues/225
When monika run with symon configuration and the unreported data is too big, it will fail.
- set the limit for amount of data to report per request (default to 100)
- when monika is started, it will first send all unreported data in batches before setting interval

fix: Initial report to symon fails if the logs db is big

---

src/components/config/index.ts
src/index.ts

This PR implements issue #232 
**How to test?**
- run `./bin/run --config <configuration url> --config-interval <chosen interval in seconds>`

Added: check configuration from URL periodically

---

src/index.ts
src/looper.ts

This PR hopefully fixes #240 and fixes #243
I moved the sanitizeConfig() function from idFeeder into the getDefaultConfig, meaning the probe sanitizing is happened AFTER validating the configuration instead of being in the looper.
This PR also emit the event SANITIZED_CONFIG for future purposes.
1. Run monika with your configuration
2. Make sure there are logs saying `Config has been sanitized`
N.A

Move sanitizeConfig out of looper and add event emitter

---

docs/package-lock.json
docs/package.json
docs/src/lib/gtag.js
docs/src/pages/_app.js
docs/src/pages/_document.js

Implementing issue #264 
- by default, analytics is disallowed
- after user agree to use cookie, then the analytics is running on every route change
1. open http://localhost:3000
2. don't click on cookies consent (or click decline. It's the same)
3. see developer console on tab network > Other
4. go to other page and see there is `no` call on url `collect?v=2...` (https://www.google-analytics.com/g/collect?v=2...)
5. clear cookies (or you can open http://localhost:3000 on new incognito)
6. accept cookie consent
7. see developer console on tab network > Other
8. go to other page and see there is `a` call on url `collect?v=2...` (https://www.google-analytics.com/g/collect?v=2...)

added: google analytics with consent

---

CHANGELOG.md
package-lock.json
package.json

- Add google analytics with consent
- Add Prometheus Metric Server
- Add HAR file config definition
- Add support for postman config file
- Add termination notif
- Write config file from har or postman
- Cleanup log display in comand line (CLI)
- Move validate response to core plugin
- Fix iphone se 2 visuals on zoomed ui
- Move notification and store from probe to event emitter
- Fix throw error when bad id
- Add dockerignore to reduce size
- Fix footer deadlink
- Fix undefined bug in CLI logs
- Change favicons

docs: add release note and changelog

---

src/components/probe/index.ts
src/components/probe/probing.ts
src/constants/event-emitter.ts
src/index.ts

1. Closing #313 
1.  The response time data lives in the config.extraData rather than than in error.response.
2. So returning config.extraData instead when not 2xx
3. Add some documentation and update the sanitize event definition
1. see Issue #313 for how to reproduce

Fix response time display error when not 2xx

---

src/components/notification/index.ts
src/index.ts
src/interfaces/data.ts

closes #361 
1. Run monika with whatsapp notification,
2. add status notification property
example: 
```json
{
"notifications": [
{
"id": "monika-webhook",
"type": "monika-notif",
"data": {
"url": "https://whatsapp.hyperjump.tech/api/notify?token=<your-token>"
}
}
],
"probes": [
],
"status-notification": "* * * * *"
}
```

Added: send status-update notification via monika-notif channel

---

docs/src/pages/guides/alerts.md
monika.example.yml
src/components/notification/alert-message.ts
src/index.ts
src/interfaces/probe.ts
src/looper.ts
src/plugins/validate-response/__tests__/index.test.ts
src/plugins/validate-response/checkers/__tests__/index.test.ts
test/components/notification.test.ts

this PR resolves #349 
1. While updating the alert guide docs to remove the subject, I also remove references to the old alert format in the guide. This is advised by Pak Ariya in team weekly checkpoint.

Changed:  Remove 'subject' property from alert config

---

src/components/notification/alert-message.ts

1. Change Error Message for Non-HTTP Error Message
1.  Catch non-HTTP error, and change the error message
1. Run `npm test`
2. Run monika with 1000+ probes, until you got ENOTFOUND, ECONNRESET, or ECONNREFUSED error. Or, you can just change `errResponseCode` variable [here](https://github.com/hyperjumptech/monika/blob/main/src/components/probe/probing.ts#L115)
with 0 for ENOTFOUND, 1 for ECONNRESET, and 2 for ECONNREFUSED.

Fixed: Change Error Message for Non-HTTP Error

---

src/plugins/metrics/prometheus/collector.ts

fix #394 
1. fix Prometheus histogram in seconds, but response time is in milliseconds
1.  change milliseconds to seconds by dividing responseTime with 1000
1. run monika with prometheus config `npm start --prometheus 3001`
2. run prometheus `./prometheus --config.file=prometheus.yml` with config like in [this article](https://medium.com/hyperjump-tech/collecting-monika-with-prometheus-9faa7d484a30)
before, the result is empty:
---
after fix, the bucket other than `le="+Inf"` is filled:

fixed: Prometheus histogram in seconds, but response time is in milliseconds

---

.eslintrc
src/components/config/validate.ts

1. Validate Symon configuration. Resolve #409.
1.  Add Symon configuratin validation
1. Run Monika with Symon configuration without projectID and/or organizationID key.
```yaml
symon:
id: jakarta
url: http://localhost:3000/api
key: 680447df-5df7-4dea-82ca-d68d45ccba04
probes:
- requests:
- url: http://example.com
```

Fixed: Validate Symon Configuration

---

src/index.ts
src/loaders/index.ts

1. Fixed Monika hangs when run with flush and logs flag. Resolve #419.
1.  Prevent command with logs or flush flag to load unneeded function.
1. Run `npm start -- -l`
2. Run `npm start -- --flush`
3. Run `npm test`

Fixed: Prevent Command with logs or flush Flag to Load Unneeded Function

---

docs/src/pages/guides/cli-options.md
src/components/config/__tests__/expected.har.json
src/components/config/__tests__/expected.postman.json
src/components/config/index.ts
src/components/config/parse-har.ts
src/components/config/parse-postman.ts
src/index.ts
test/index.test.ts
test/testConfigs/simple.postman_collection.json

This PR resolves #422 
1. Allow `--har` and `--postman` to be combined with `-c/--config`
1.  Probes from `har` and `postman` file will always override configurations passed to `--config`
2. When no additional config provided, `desktop` notification type will be default
3. `--har` and `--postman` are still exclusive against each other
- `npm run -- -c /path/to/notifications/config --har test/testConfigs/harTest.har`
- `npm run -- -c /path/to/notifications/config --postman test/testConfigs/simple.postman_collection.json`

Allow merge from --postman and --har with --config

---

CHANGELOG.md
package-lock.json
package.json

- Update Raspberry Pi tutorial (#380)
- Add city and ISP in notification (#387)
- Docs: Update Monika Documentation Structure (#393)
- Compress binaries as ZIP when Releasing (#396)
- Tests: Add stub getPublicNetworkInfo to make test run faster (#401)
- Add alert for individual request (#390)
- Support an object for TLS check domains (#388)
- Docs: Add Yaml example configs (#404)
- Validate symon configuration (#413)
- Add support multiple args to config flag (#407)
- Add Larksuite notification (#425)
- Add Monika and OS Version in Notification Message (#429)
- Allow merge from --postman and --har with --config (#427)
- Clean up average response time in the status summary (#398)
- Offload and centralized side effect only function (#392)
- Reorganize Event Emitter (#399)
- Attach incident …

Release 1.6.1

---

src/components/config/index.ts
src/index.ts

This PR resolves #437 
1. Fix `-c/--config` flag to have `['./monika.json/yml/yaml']` as default
1. Change return value of `getDefaultConfig()`
2. Workaround the impact of removing `-c/--config`'s exclusivity against `--postman` and `--har`
1. If you don't have `monika.json/yaml/yml` file, `cp monika.example.yml monika.yml`
2. `npm run start` should properly use `./monika.yml`

fix: resolve default config as array

---

src/components/notification/__tests__/process-server-status.test.ts
src/components/notification/process-server-status.ts

This PR fixes #443 
The problem is exactly as @nicnocquee comment here https://github.com/hyperjumptech/monika/issues/443#issuecomment-928258005
1.  set `shouldSendNotification` to true only when state transition happen
2. add test to validate it
1. npm test

Fix: Notification was sent when no state transition happen

---

src/components/config/index.ts

fixes #441 
Monika does not reload because of a mistake in the version assignment to the updated config.
1. run monika with any config
2. update the config while monika is running
3. check the terminal, it should display something similar to
```sh
WARN: config file update detected
Restarting Monika. ...
```

fix: config file update not detected

---

src/components/notification/alert-message.ts
src/components/notification/channel/lark.ts
src/components/notification/channel/teams.ts
src/interfaces/notification.ts
src/jobs/summary-notification.ts

This PR resolves #449 
1. Move version and platform info to new line for Ms Teams and Lark notification channel
1.  Add `version` to `meta` field
2. Add new line to Lark and Ms Teams notification channel
1. To immediately trigger alert, we can use below config
```
"incidentThreshold": 1,
"alerts": ["response-time-greater-than-1-ms"]
```
2. `npm run start`
Screenshot

chore: move version to new line

---

src/components/config/fetch.ts
src/components/config/index.ts
src/components/config/parse.ts
src/index.ts

fixes #457 
load remote yaml file into javascript object after fetching
`npm start -- --config https://raw.githubusercontent.com/hyperjumptech/monika/main/monika.example.yml`
I also improve the handling of config file not found. Previously to handle this, the `flags.config` property was deleted first. I think this is not good because there is possibility that the `flags.config` value is gonna be needed later

Fixed using yaml format with remote configuration

---

src/components/notification/channel/desktop.ts

1. Fixes issue #453 
1. `type()` returns "Windows_NT" for Windows OS, so changing the case from "Windows NT" to "Windows_NT" fixed this issue
1. Boot Windows 10
2. Run this or any config in Monika
```notifications:
- id: desktop
type: desktop
probes:
- id: sample_1
name: Sample Request
requests:
- method: GET
url: https://reqres.in/api/users/23
alerts:
- query: response.time > 200
message: Response time is {{ response.time }} ms, expecting less than 200ms
- query: response.status != 200
message: Status code is not 200. I think their service is down.
- query: isEmpty(response.body)
message: Response body should not be empty!
```
3. You should see the desktop notification

fix: windows desktop notification doesn't show

---

src/index.ts
src/symon/index.ts

This PR adds the ability to SymonClient to send Monika's status when initiated, terminated and exited.
1. npm start -- --symonUrl `<your-symon-url>` --symonKey `<your-symon-api-key>`

SymonClient: adds send status when initiated, terminated and exited

---

package.json
src/index.ts

This PR fixes #532 
Use `@oclif/errors`error handler according to the [docs](https://oclif.io/docs/error_handling)
It seems that people are getting the same error when printing help or version ([Exhibit A](https://githubmemory.com/repo/oclif/oclif/issues/427) and [Exhibit B](https://githubmemory.com/repo/oclif/errors/issues/67)). Using the `@oclif/errors` will [respect any EEXIT error (including ExitError) (https://github.com/oclif/errors/releases/tag/v1.3.5) 
1. Run npm run start -- -v
2. It should print version without errors

Fix: Error Handling with Oclif

---

docs/src/pages/guides/probes.md
src/components/probe/probing.test.ts
src/components/probe/probing.ts

This PR resolves #562 
1. Add support for `application/x-www-form-urlencoded` request
1. Add check for `Content-Type` request header in case-insensitive manner.
2. If `Content-Type` is `application/x-www-form-urlencoded`, serialize body into URL-safe string.
1. Sample config
```
{
"probes": [
{
"requests": [
{
"url": "http://0.0.0.0:8080/login",
"method": "POST",
"body": { "username": "example@example.com", "password": "example" }
}
],
"incidentThreshold": 5,
"recoveryThreshold": 5,
"alerts": ["response-time-greater-than-200-ms"]
}
]
}
```
2. `npm run start -- -c <path to sample config>`
3. To run unit tests: `npm run test`

added: support for form-urlencoded

---

.eslintrc
docs/src/pages/guides/probes.md
monika.example.json
monika.example.yml
package.json
src/components/config/validate.ts
src/components/logger/request-log.ts
src/components/probe/index.ts
src/components/probe/probing.ts
src/interfaces/request.ts
src/plugins/validate-response/checkers/index.ts
src/utils/ping.ts

1. Implements ping as a request
2. Closing #551
1. Add documentation for ping
2. Add ping as a type of probe request
```yaml
probes:
- id: 'ping_test'
name: ping_test
description: requesting icmp ping
interval: 10
requests:
- url: http://google.com  
ping: true
```
3. Update validation to account for ping host not need http/https, and filtering for it.
4. Add alert if ping is not alive.
5. Update logger to map ping result properly via our standard logger/output.

Add ping feature

---

docs/src/pages/guides/status-notification.md
src/components/config/index.ts
src/components/notification/alert-message.ts
src/utils/public-ip.ts

1. Closing issue #572 
2. Using `--status-notification "* * * * * *"` runs the stun checking rapidly
1. Ooook so it turns out we have an undocumented feature supporting per-second crons intervals
2. The cron package we use supports a six field cron syntax "* * * * * *" for seconds interval
3. Added more documentation under guides/status-notification
4. Refactor the monikaInstance() to not hit stun all the time.
1. call monika with `--status-notification "* * * * * * "`
2. should not have stun called every second (should still be 20s as default)

Update Cron Documentation

---

src/index.ts
src/symon/index.ts

This PR fixes #581 
This PR adds an optional `--symonLocationId` flag to assign a location to a Monika instance when the handshake process is being run. So, a user who uses Monika in Symon mode doesn't have to run-assign-restart the Monika instance anymore.
1. Run this command `npm run start -- --symonUrl=<SYMON_URL> --symonKey=<SYMON_KEY> --symonLocationId=<SYMON_LOCATION_ID>`
2. You should see logs similar to this (ignore the console.log as it is only for development)
3. Remove existing connected Monika instance
4. Run this command again without the location ID `npm run start -- --symonUrl=<SYMON_URL> --symonKey=<SYMON_KEY>`
5. You should see logs similar to this (ignore the console.log as it is only for development)
You may have to wait until the PR in Symon to handle the Location ID …

SymonClient: Add --symonLocationId flag for Symon handshake process  

---

src/components/config/index.ts
test/index.test.ts

Resolves #601 
1. Provided `--insomnia` without `monika.json` / `monika.yml` file in CWD will throw error
1.  Evaluate insomnia flag existence
2. Add test to run insomnia flag
1. `rm monika.yml && rm monika.json`
2. `npm run start -- -insomnia src/components/config/__tests__/petstore.insomnia.yaml`
3. Monika should run without config error

fix insomnia flag error without -c default in CWD

---

.github/workflows/docker-push.yml
.github/workflows/node.js.yml
.github/workflows/npm-publish.yml
.github/workflows/publish-snap.yml
.github/workflows/upload-binary.yml

This PR updates the GitHub workflows so that we can run them manually in addition to the existing triggers.

Update workflow to allow manual trigger

---

src/index.ts

1. Fix default monika config directory. It resolves #644.
1.  Add `path.dirname` to get the directory absolute path
1. Run `npm start` with `monika.yaml` in the project root directory
2. Build Monika binary, put the `monika.yaml` in the same directory, run the binary
https://user-images.githubusercontent.com/15191978/163116262-05fc6091-9574-47cc-82ba-82c5ce8364c9.mp4

Fix: default monika config directory

---

docs/src/pages/quick-start.md

* Prioritize installation via native package manager
* Include self-contained instruction per operating system

docs: Revamp the installation quick-start guide

---

.github/workflows/docs.yml

The workflow docs failed because the environment variables are needed not only during the algolia steps but also during the build step. This PR fixes it by moving the environment variables out of the steps.

fix workflow to deploy docs

---

.github/workflows/docs.yml

[lockfile](https://nodejs.dev/learn/the-package-lock-json-file) for `docs/` exists, therefore the dependencies must be deterministically installed.
Use `npm ci` instead of `npm install`.
Run `npm ci`.

CI: honor the lockfile, use `npm ci` instead

---

.github/workflows/docs-build.yml

This PR adds a workflow that will run whenever a Pull Request is opened which changes something in docs/ directory. This way we can make sure the docs can be built before merging it into main.

Add workflow to build the docs when needed in pull request

---

.github/workflows/docs-build.yml

The docs-build workflow will always fail if the Pull Request comes from outside this repository. Changing the trigger to pull_request_target should fix it.

Change the trigger for doc build workflow

---

.github/workflows/node.js.yml

This PR fixes the failing workflow when executing `npm ci` in node 16.15.

fix node js workflow

---

docs/src/components/NavIndex.js
docs/src/pages/guides/examples.md

1. fix  #702 
1.  change min width > 1024 so the ToC placed on the right side of the docs
2.  change max width < 1023 for mobile
**this display above 1024 pixel**
----
**this display below 1024 pixel**
------
I found the sidebar doesn't appear exactly 1024 pixels, maybe this can be made into new issue

Fix: responsive table of content placement (#702)

---

src/components/probe/probing.ts

This PR solves #725 
Logged using Axios' interceptors
Config:
```yml
probes:
- id: '1'
name: Probing Github
description: simulate html form submission
interval: 10
requests:
- method: GET
url: https://reqres.in/api/users
timeout: 7000
- method: GET
url: https://reqres.in/api/users/{{ responses.[0].data.data.[0].id }}
timeout: 7000
body:
id: '{{ responses.[0].data.data.[0].id }}'
id_second: '{{ responses.[0].data.data.[0].id }}'
alerts:
- status-not-2xx
- response-time-greater-than-2000-ms
```

feat: adds support request chaining for body

---

docs/src/pages/guides/notifications.md

1. 767/Docs: Wrong link in Notification page
1. Go to https://monika.hyperjump.tech/guides/notifications
2. click status-not-2xx
3. 
https://user-images.githubusercontent.com/47026826/178926181-1ebfadcd-d34a-4745-8ac8-4eb4846c2683.mov

Docs: Change link in Notification page(#767)

---

docs/src/pages/guides/notifications.md
docs/src/pages/index.js

1. Link to whatsapp for business does not work
1. Update the toc link
2. Update some notif example to emphasize array of strings and strings (vs number)
1. Go to /docs, run `npm run dev`
2. Go to localhost:3000 on your browser
3. Click on notification and try all the notification shortcut

Doc: Fix Whatsapp toc link in notification page

---

docs/src/pages/guides/examples.md

1. Implements #757 
2. Missing example for request chaining in body
1.  Adding specific example where previous request is used in body
2. Test the example
1. Use the following monika.yaml
```yaml
probes:
- id: probe-01
name: 'body from resonse'
interval: 10
requests:
- url: https://reqres.in/api/users/1
method: GET
timeout: 5000
saveBody: false
headers:
Content-Type: application/json; charset=utf-8
- url: https://reqres.in/api/login
method: POST
timeout: 1000
headers:
Content-Type: application/json; charset=utf-8
body:
email: '{{ responses.[0].body.data.email }}'
password: password
```
2. Then run `monika -c monica.yaml -s 0`

Add example for request chaining in body payload

---

monika-config-schema.json
monika.example.yml

1. Implements #797 
2. Forgot status-notification validation
1. Add "status-notification" 
2. Add status-notification in example.yaml
1. Use this latest json schema for testing, On VSCode goto File --> Preferences, type "schema" above and you should see:
2. Under the settings.json we can define a specific schema (this update file) to a test file say `test.yaml`:
(your original yaml setting will not be affected/modified)
3. You might need to quit vscode and start it again for the settings to be updated.
4. Then create your teset config file, `test.yaml`:
```yaml
probes:
- id: probe-01
name: 'test'
interval: 10
requests:
- url: http://errorhttpbin.org/status/400
method: GET
timeout: 5000
saveBody: false
headers:
Content-Type: application/json; charset=utf-8
notifications:
- id: …
```

Add status notification validation

---

docs/src/pages/guides/cli-options.md
src/components/probe/index.ts
src/components/probe/probing.test.ts
src/components/probe/probing.ts
src/index.ts
src/looper/index.ts

1. Resolve #818 
1.  Add a new flag `--follow-redirects`. Set to zero to disable following redirects or to a certain number to tell Monika to follow redirects as many times as specified here. Seems like the cause of connection timeout when there are many probes is because of the redirect following. Setting this flag to zero resolves the problem.
2. Update doc.
1. Create monika.yml with the content from [here](https://gist.github.com/nicnocquee/0aae7746041c700fd3b952c826703ada).
2. Run monika from this PR: `rm -rf monika-logs.db && npm run start -- -c ~/Downloads/monika-experiments/monika.yml --follow-redirects 0`
When `--follow-redirects` is zero,
First cycle, the probe monika.hyperjump.tech is ok
Second cycle, the probe monika.hyperjump.tech is still ok
When running with …

Add follow-redirects flag

---

docs/src/pages/guides/cli-options.md
src/index.ts
src/looper/index.ts

1. Resolve #807 
1.  Add a new flag `max-start-delay`. When set greater than zero, Monika will start probing the probes in slightly different time but still within the specified max-start-delay. Default value for max-start-delay is 60000 (which corresponds to 1 minute).
2. Add documentation about this new flag.
1. Use the following monika config and save it as monika.yml
```yaml
notifications:
- id: desktop
type: desktop
probes:
- id: "probe-0"
name: "Probe 0"
interval: 30
alerts:
- query: "response.status != 200"
message: " Http Response status code is not 200!"
requests:
- method: GET
url: "https://monika.hyperjump.tech/"
timeout: 10000
- id: "probe-1"
name: "Probe 1"
interval: 30
alerts:
- query: …
```

Add max-start-delay flag to prevent probes from starting at the same time

---

docs/src/pages/guides/alerts.md

#799 Docs: example in alerts page is not valid 
change the example in alerts documentation page
1. create monika.yml
2. copy examples on alert documentations page to monika.yml
3. make sure there is none validation error

fix(docs): [799] fix documentations on alert example

---

docs/src/pages/guides/probes.md

#796 Docs: Invalid example on probes page
fix configuration examples on probes page
1. create monika.yml 
2. copy example from probes page to monika.yml
3. make sure there are no error shown on the vscode

fix(docs): [796] fix configuration examples on probe page

---

src/components/notification/channel/dingtalk.ts
src/components/notification/channel/googlechat.ts
src/components/notification/channel/slack.ts
src/components/notification/channel/teams.ts

#815 Response time in status notification is not correct
change minimum response time value to display minResponseTime instead of maxResponseTime 
1. set monika config with slack/teams notifications and update status notifications :
```
notifications:
- id: 0001-slack,
type: slack
data:
url: https://hooks.slack.com/services/slackwebhookurl
status-notification: 0 * * * *
```
2. run monika until it send status notifications update
3. it should show status update notif with true max and min response time

fix(notifications): [815] change min response time

---

docs/src/pages/guides/notifications.md

fix #800 Docs: example in notifications page is not valid
change the example in notifications documentation page
1. create monika.yml
2. copy examples on notifications documentations page to monika.yml
3. make sure there is none validation error

fix(docs): fix documentations on notification example

---

.github/workflows/auto-pr-schemastore.yml

1. Fix workflow error
2. Test repo was using `main`, but actual schemastore repo is using `master`
1.  Update the target branch to `master`

Update target branch 

---

docs/src/components/markdown.module.css

1.  fix #826 
1.  change background gradient text link to purple with `text-purple-monika` class
here the screenshoot
Is this enough?

change link color in docs to purple

---

.dockerignore
Dockerfile

This PR 
- fixes monika not running in symon mode. For some reason it needs to use node 16. But cannot use node 16.15 since for some reason npm ci fails with it.
- reduce the size of the docker image. Before it was 645MB. With this PR it becomes 261MB.

Fix symon not running

---

package-lock.json
package.json
test/bats/cli.bats

This PR contains:
- `bats-support` causes package installation failed, since it has already been installed when we install `bats-assert` so we no need to install it individually.
- Updated the Bats tests.

removes 'bats-support' from deps and update the Bats tests

---

docs/src/pages/guides/cli-options.md
package.json
src/components/config/__tests__/create-config.test.ts
src/components/logger/request-log.ts
src/components/probe/index.ts
src/components/probe/probing.test.ts
src/components/probe/probing.ts
src/context/index.ts
src/index.ts
src/looper/index.ts

1. Closes #848 
2. Improve how flags are passed into functions
1. Refactor function parameters using objects
2. Add monika flags as paramenter inputs for easier checking/access
3. Checks for -s == -1 to disable STUN blocking
1. First we want to block stun server. Find out the stun server available from your provider/location. Ping the stun to get its IP like below (your ping and ip result will likely be different than the example).
```bash
ping stun.l.google.com
PING stun.l.google.com (172.253.118.127) 56(84) bytes of data.
64 bytes from sl-in-f127.1e100.net (172.253.118.127): icmp_seq=1 ttl=106 time=22.5 ms
64 bytes from sl-in-f127.1e100.net (172.253.118.127): icmp_seq=2 ttl=106 time=22.8 ms
64 bytes from sl-in-f127.1e100.net (172.253.118.127): icmp_seq=3 ttl=106 time=23.6 ms
64 bytes …
```

Make STUN non blocking

---

src/components/logger/history.ts

It fixes a bug which occurs when running `monika --summary`:
```
> monika --summary
ERROR: Summary notification: Cannot read property 'probes' of undefined
```
I only added a check if `config` is defined in `getSummary()` function. It seems to be undefined when running the function in CLI. The value on number of probes in CLI is taken for PID file, so it's still OK if config is undefined.
Just run `monika --summary`

fixed summary bug

---

monika-config-schema.json

1. Part of #858 
2. Part of #859 
3. Update json schema for the new probe requests
1.  Add entries for redis and postgres requests
1. Use the monika-config.schema.json in this pr. (For how to setup the yaml see PR: #743
2. Create a config.yml file something like below:
```yaml
probes:
- id: checking-redis
name: ping redis
alerts:
- query: response.status != 200
message: redis not available
redis:
- host: 172.17.0.1 // mising port
- id: checking-postgress
name: ensure postgress is alive
alerts:
- query: response.status != 200
message: redis not available
redis:
- host: 172.2.1.1
host: 1.2.3.4 // non unique error
port: 5432
notifications:
- id: desktop-01
type: desktop
```
3.  You should get multiple errors …

Update JSON schema for redis/postgres requests

---

src/index.ts
src/looper/index.ts

This PR fixes two bugs:
1. Fixes `Alert ID` error when sending event to symon.
2. Fixes error when saving to local db.

fix: deprecationHandler and sanitizeProbe alert bugs

---

docs/src/pages/guides/probes.md
monika.example.yml
src/components/http-request/http-request.test.ts
src/components/http-request/index.ts
src/interfaces/request.ts
src/monika-config-schema.json

1. Adding option to allow probing invalid ssl endpoint
1.  Adding configuration `allowUnauthorized` and used in creating http request, if detected this will make https agent with `rejectUnauthorized` set to false
1. Make probe request to `https://expired.badssl.com/` or other invalid ssl cert from badssl.com

adding option to allow probing invalid ssl endpoint

---

.github/workflows/auto-pr-schemastore.yml
src/monika-config-schema.json

1. Create a PR when monika-config-schema.json
2. AutoPR was broken
1. Base repo changed to SchemasStore/schemastore
2. Fork is the local fork (hyperjumptech/schemastore)
3. Add a schemastore testing phase `make`
4. Made sure monika-config-schema.json passes schemastore ci testing (no 3 above)
1. The following sample should work:
(with "missing host error id-postgres"
```yaml
notifications:
- id: unique-id
type: desktop
probes:
- id: 'id-1'
name: Example
description: Probe
interval: 5
requests:
- url: 'https://httpbin.org/status/200'
alerts:
message: 'AAALEEEERT!!!'
- id: 'id-postgres'
name: Postgres test
description: Test schema
postgres:
- uri: 'postgres://user:password@172.1.0.1/database'        
- username: …
```

Update auto pr workflow

---

src/components/probe/index.test.ts
src/components/probe/index.ts

1. Fix send recovery notification when Monika starts. This will resolves #933.
1.  Add conditional statement to prevent send notification when the first event is up for non Symon mode
1. Run Monika with multiple probes

fix: prevent send backup notification when Monika starts

---

src/components/config/index.ts
src/components/config/validate-config.ts

1. Closing #938 
2. Improves error message on config validation
1.  Parse the validation errors back to the user
2.  When not in testing mode, do not throw error on validation fail
1. use a bad config like this:
```yaml
notifications:
- id: unique-id
type: desktop
probes:
- id: 'id-test'
name: test probe
description: test db connection monitor
postgres:
- host: 172.17.0.1
portk: 3306
username: user        
password: pass
database: db
alerts:
message: 'D-E-D! DB is DED'
```
3. then run `bin/run-dev -c config.yaml`
4. you should get a detailed error
Before fix
After fix (when run normally)
After fix (with test env)

parse json validation error

---

src/monika-config-schema.json

1. Closes #954 
2. Fixes error when using using config generator
1.  Readd query as an allowable alert field
2. Allow for `query` but recommend `assertion` as default on the json-schema
1. Use the following config.yaml 
```yaml
notifications:
- id: unique-id
type: desktop
- id: mailtrap-id
type: smtp
data:
hostname: smtp.myserver.com
port: 25
username: user
password: pass
recipients: ["me@myserver.com"]
probes:
- id: 'id-1'
name: Http-Request
description: http type probe
interval: 5
requests:
- url: http://0.0.0.0:7001/v1/hello
alerts:
message: 'user message! Response NOK Status!'
- query: response.time > 2000
message: 'user message! Response too Slow!'
```
3. `bin/run-dev -c config.yaml -s -1`
4. Should run …

Add query support

---

src/symon/index.ts

Fix Monika crashes when send an incident/recovery event. It resolves #959.
Handle the unhandled error
1. Make the `/api/v1/monika/events` endpoint return HTTP status code < 200 or >= 300 on Symon
2. Run Symon
3. Run Monika
Monika keeps running after get a fail response from Symon

Fix: Monika crashes when send an incident/recovery event

---

.eslintrc
src/components/tls-checker/index.ts
src/interfaces/certificate.ts
src/jobs/tls-check.ts

Improve Monika config type for TLS checker
Replace the type for the Monika's certificate property
```yaml
certificate:
domains:
- example.com
- expired.badssl.com
- domain: example.com
options:
path: '/foo'
reminder: 30
```
```typescript
export interface Certificate {
domains: string[]
// The reminder is the number of days to send notification to user before the domain expires.
reminder?: number
}
```
```typescript
import type { RequestOptions } from 'https'
type DomainWithOptions = {
domain: string
options?: RequestOptions
}
export type Domain = string | DomainWithOptions
export interface Certificate {
domains: Domain[]
// The reminder is the number of days to send notification to user before the domain expires.
reminder?: number
}
```
Run Monika with the following config
```yaml …
```

Fixed: Improve Monika Config Type for TLS Checker

---

.github/workflows/node.js.yml
package.json

Make [MSW](https://github.com/mswjs/msw) run on Node.js v18. Relate to [PR 950](https://github.com/hyperjumptech/monika/pull/950).
Add NODE_OPTIONS environment variable when run unit test to use old fetch from node < 18 when running the test.
1. Run `npm test` using Node.js v16
1. Run `npm test` using Node.js v18.

Chore: Make MSW Run on Node.js v18

---

package-lock.json
package.json
src/components/http-request/http-request.test.ts
src/symon/bree/report.ts
src/symon/index.test.ts
src/symon/index.ts

This PR moves the reporting as a separate worker by using Bree.
1.  Install Bree
2. Moved the reporting process to a separate worker file
1. Run Symon
3. Run Monika in Symon Mode
You may see a flow for modifying the report job like this:
```
bree.remove()
bree.add()
bree.start()
```
This is because there is no built in function to modify current job (as explained in https://github.com/breejs/bree/issues/169)

SymonClient: Use Bree for Reporting to Symon

---

package-lock.json
package.json
src/components/notification/process-server-status.ts
src/index.ts
src/utils/probe-state.ts

1. Issue #982 and also fixes the error when running `monika -v` which causes the prod_test to fail.
1.  Update the `catch` function in `src/index.ts` to exit immediately if the caught error contains `EEXIT: 0`. This string is in the error when oclif tries to exit normally for example after printing out the version.
2. Update the xstate then add `predictableActionArguments: true` as advised in the warning message.
1. `npm pack`
3. `npm install -g ./hyperjumptech-monika-*.tgz`
4. `monika -v` and `npm run prod_test`
```shell-session
npm pack
> @hyperjumptech/monika@1.15.0 prepack
> npm run clean && tsc -b && oclif manifest
> @hyperjumptech/monika@1.15.0 clean
> rm -rf coverage lib tsconfig.tsbuildinfo oclif.manifest.json
›   Warning: oclif update available from 3.0.1 to 3.4.2.
wrote manifest …
```

fix error when running -v and remove the unnecessary message

---

.github/workflows/node.js.yml

Before this PR:
After this PR:
Note that it correctly grabs and installs Node.js v16.19 (the latest in the 16.x series).

CI: fix Node.js version matrix

---

src/index.ts
src/looper/index.ts

1. Clean up warning messages
1. Fix an old default alert message
2. Show alerts.query deprecation warning only if used
1. use the following config
``` yaml
probes:
- id: '1'
name: 'status-200-test'
requests:
- url: https://httpbin.org/status/201
alerts:
- assertion: response.status < 200 or response.status > 299
message: HTTP Status is not 200
- assertion: response.time > 2000
message: Response time is more than 2000ms
notifications:
- id: desktop
type: desktop
```
2. Run `monika -c config.yaml` from above
3. Update the alert entry to 'alerts.query' to trigger the deprecated warning
if alerts.query used

update warning messages

---

.github/workflows/node.js.yml

This PR solves #1031 
1. Add some steps to building Monika using PKG according to the environment matrixes
2. Run the built Monika by checking the version (previously when it broke, it showed an error even if we checked the version)
1. Run the workflow manually
No, but take a look at the action in my fork: https://github.com/dennypradipta/monika/actions/runs/4719370222/jobs/8370101810
1. Approximately 9~10 extra minutes are needed to build and run the Monika binary.
2. In the `build-on-node-js-18` action, I use node16 because there is no explicit node18 target in pkg (nodeRanges available: node8, node10, node12, node14, node16 or latest)

CI: Test out the built binaries from PKG in CI

---

src/components/config/get.test.ts
src/components/config/get.ts
src/components/config/index.ts

As a part of refactoring, I extracted the get config function to make it reusable in other part of the code
1. Split the sanitize flag, get config, merge config, and update config phase
2. Extract the get config function
1. Run the test
2. Run Monika as usual

Refactoring: Extract the Get Config Function

---

src/components/config/index.test.ts
src/components/config/index.ts
src/components/logger/startup-message.test.ts
src/components/logger/startup-message.ts
src/components/notification/schedule-notification.test.ts
src/components/notification/schedule-notification.ts
src/components/probe/index.ts
src/components/probe/prober/http/index.ts
src/index.ts
src/loaders/index.ts
src/looper/index.ts
src/symon/index.test.ts
src/symon/index.ts

Separate update config from initialize config
1. Add some tests
2. Move Monika config state from variable to context
3. Extract isSymonMode function
4. Change the implementation of Monika config watcher from generator functions to simple for loop. It makes the watcher more efficient because it doesn't need to skip the first loop to run.
5. Separate update config from initialize config
1. Run `npm test`
2. Run Monika as usual

Refactoring: Separate Initialize and Update Config

---

src/index.ts
src/looper/index.ts

Use abort controller to cancel running probe. Currently, when there is a config changes, probe interval is clear. But it only clear the interval, not the running request. I added abort controller to make it easy to cancel the request in the future. 
1. Implement abort controller
2. Clear the interval when abort is called
1. Run Monika
2. Change the config
https://github.com/hyperjumptech/monika/assets/15191978/5f70d592-cec3-4065-b3f6-a419a6562de8

Refactor: Use Abort Controller to Cancel Running Probe

---

src/components/config/validation/validator/request.ts
test/index.test.ts

Improve error message when request URL is not using http/https
Add url to the error message to help point out which url cause the error
Run Monika with the following config
```yaml
probes:
- id: "Yahoo News Japan"
requests:
- url: news.yahoo.co.jp
```

Feat: Improve Error Message When Request URL is not Using Protocol

---

.github/workflows/teams-notify.yml

1. This PR fixes a vulnerability where the issue announcement workflow is vulnerable to injection via a pull request or issue (see https://cycode.com/blog/github-actions-vulnerabilities/). Even though it does not check out code from a PR the workflow has a GITHUB_TOKEN with write access. It is possible to obtain this by dumping the runner's memory. I am happy to prove it if you would like.
1.  The fix is to limit the workflow permissions to read on issues and PRs and to save the titles to environment variables prior to using them in a script run step.
1. To validate the bug, create an issue with the following title `TestIssue" && echo "RCE" && ls -la / && echo "FooBar`

Fix GitHub Actions Injection Vulnerability

---

.github/workflows/auto-pr-schemastore.yml
.github/workflows/docker-push.yml
.github/workflows/docker-release-from-tag.yml
.github/workflows/docs-build.yml
.github/workflows/docs.yml
.github/workflows/nightly-release.yml
.github/workflows/node.js.yml
.github/workflows/npm-publish.yml
.github/workflows/package-notification-publish.yml
.github/workflows/publish-snap.yml
.github/workflows/sonar-cloud.yml
.github/workflows/teams-notify.yml
.github/workflows/upload-binary.yml

1. Improve security of github action workflow
2. References the [recommendations from here](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) 
3. Also [this blog here](https://cycode.com/blog/github-actions-vulnerabilities/) has some decent examples
1. Limit the scope of issued GITHUB_TOKEN to explicitely be type "read"
2. Sanitize "run" type actions to minimize injection ex: `run: echo ${{ sometext can be iffy }}`

Limit scope of tokens

---

packages/notification/channel/teams.ts
src/components/probe/prober/http/index.ts

1. Empty URL field in Notification
2. Fixes issue #962
1.  Display URL or ProbeID if URL not exist.
1. Use a config where you probe a postgre db or a redis cache:
```yaml
probes:
- id: 'redis-1'
name: 'redis-test'
redis:
- host: 192.168.0.1
port: 6379
alerts:
- assertion: response.status < 200 or response.status > 299
message: HTTP Status is not 200
- id: postgres-111
interval: 3
postgres:
- uri: postgres://user:password@192.168.0.2:5432/mydb
alerts:
- assertion: response.status < 200 or response.status > 299
message: HTTP Status is not 200
notifications:
- id: desktop
type: desktop
- id: teams-001
type: teams
data:
url: https://yourcompany.webhook.office.com/webhookb2/1122335566aabbccdded/IncomingWwebhood/ …
```

Update Teams Notifications for NonHTTTP Probes

---

packages/notification/channel/__test__/webhook.test.ts
packages/notification/channel/webhook.ts
src/components/probe/index.test.ts

Fix webhook notification is not working
https://github.com/hyperjumptech/monika/assets/15191978/322c37c2-7c34-4ac3-bbb9-632bba77c6b6
https://github.com/hyperjumptech/monika/assets/15191978/0673c848-768e-4c79-8f6e-814e94f9c949
1. Run a server that print the request body
2. Run Monika with the following configuration
```json
{
"name": "webhook-notification",
"version": "0.0.1",
"description": "A server to test webhook notification",
"main": "index.js",
"scripts": {
"dev": "nodemon index.ts",
"test": "echo \"Error: no test specified\" && exit 1"
},
"keywords": [
"webhook",
"monika"
],
"author": "haricnugraha@gmail.com",
"license": "MIT",
"dependencies": {
"express": "4.18.2"
},
"devDependencies": {
"@types/express": "^4.17.17",
"@types/node": "^20.5.0",
"nodemon": "^3.0.1",
"ts-node": …
```

Fix: Webhook Notification is Not Working

---

src/components/notification/__tests__/alert-message.test.ts
src/components/notification/alert-message.ts
src/components/probe/index.test.ts
src/components/probe/prober/http/index.ts
src/interfaces/probe.ts
src/plugins/metrics/prometheus/collector.test.ts

Fix undefined alert query when notification message set to empty string
1. Run Monika with the following configuration and add your chosen notification
```yaml
probes:
- id: custom-alert
requests:
- url: https://httpbin.org/status/201
interval: 5
alerts:
message: ""
```

Fix: Undefined Notification Message

---

src/components/probe/index.ts
src/components/probe/prober/factory.ts
src/components/probe/prober/http/index.ts
src/components/probe/prober/index.ts

Make the HTPP prober a subclass
- Create implementation of http prober based on base prober
- Make the base prober lean by removing unneeded code
- Add the http prober to the prober factory
- Inline the probe non http function
1. Run `npm run test`
2. Run monika as usual

Refactor: Make HTTP Prober a Subclass

---

src/components/config/get.ts

Fix non HTTP prober is not running
Remove empty array as fallback to undefined
https://github.com/hyperjumptech/monika/assets/15191978/c0b280ca-ebb8-4493-9d23-071ea8022130
1. Run local probe target. Run `cd dev && docker compose up`
2. Run Monika with the following configuration. Run `npm start`
```yaml
probes:
- id: mariadb
interval: 2
mariadb:
- host: localhost
port: 3306
username: mariadb_user
password: mariadb_password
database:
- id: mysql
interval: 2
mysql:
- host: localhost
port: 3307
username: mysql_user
password: mysql_password
database:
- id: mongo
interval: 2
mongo:
- uri: mongodb://mongo_user:mongo_password@localhost:27017
- id: postgres
interval: 2 …
```

Fix: Non HTTP Prober is not Running

---

src/looper/index.ts

Change a typo from 20000 to 2000 in the response time default alert Message
Change 20000 to 2000
1. Run Monika with the following configuration
```yaml
probes:
- id: default-alert
requests:
- url: https://google.com
```

Fix: Change Response Time Default Alert Message

---

src/components/config/index.test.ts
src/components/config/index.ts

Monika exits when connected to Symon with an empty probe. It will fix #1121.
Don't throw error when config is empty in Symon mode.
1. Run Symon.
2. Run Monika in Symon mode.
3. Connect Monika through operator dashboard.
4. Assign to some probe.
https://github.com/hyperjumptech/monika/assets/15191978/666714a2-0c7a-4fb8-85a4-0fe61aa1f228

Fix: Monika exits when connected to Symon with an empty probe

---

test/index.test.ts

Currently, when testing Monika, it continues to run in the background even though we no longer need it. To make it exit, we need to set the repeat flag to 1.
Set Monika's repeat flag to 1 in the `./test/index.test.ts` file.
Run `npm run clean && NODE_ENV=test mocha --require ts-node/register ./test/index.test.ts`.
https://github.com/hyperjumptech/monika/assets/15191978/0718d37a-4009-403a-80c7-e412a7c1d7ae
https://github.com/hyperjumptech/monika/assets/15191978/5f06b6c7-d809-4f58-b64b-7b4f77c6b860

Test: Set Monika Repeat Flag to 1 in the Command Test

---

CHANGELOG.md
package-lock.json
package.json

1. Updates for release v1.15.9
- Fix: Monika Handshake to Symon Crashes If There is No Internet Connection (#1135)
- Fix: Monika Can not Send Alert to Symon (#1130)
- Fix: Monika exits when connected to Symon with an empty probe (#1123)
- Fix: change 20000 to 2000 for response time default alert log (#1120)
- Add: custom http response from axios in docs (#1133)
- Deprecate: Incident and Recovery Threshold (#1129)
- Removed: isProbeResponsive Field (#1128)
- Docs: Remove incident and recovery threshold (#1127)
- Test: Set repeat flag to 1 for Monika command test (#1126)
- Restructure: PING request (#1125)
- Add: A new flag to use the Symon API version (#1124)
- Refactor: Set the Probe Alert ID as a Mandatory Type (#1122)
- Feat: Replace Incident and Recovery Threshold Mechanism with …

Prepare for release v1.15.9

---

.github/workflows/auto-pr-schemastore.yml

1. Fixes issue #1142 
2. Broken auto PR github action
1. An unneeded step was accidentally added to the pipeline to fix a previous pipeline issue
2. Remove offending step
Context: 
The line `npm run build -w packages/notification` is for building monika to eventually test. But in that job, it is for building and testing schemastore not Monika.

Issue 1142 - Ci/CD broken workflow

---

src/components/config/validation/validator/probe.ts
src/monika-config-schema.json
test/index.test.ts
test/testConfigs/probes/valid-http-method.yaml

Allow [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) and [TRACE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE) HTTP method.
1. Allow the HTTP method in the validation and json schema. 
2. Add test.
1. Run `npm start -- -c ./test/testConfigs/probes/valid-http-method.yaml`.
2. Run the unit test.

Feat: Allow "CONNECT" and "TRACE" HTTP method

---

package.json

This PR includes the lib/workers directory when running npm pack
Add the lib/workers in the package.json
`npm pack`
Running from the installed pack:

Fix: Include the workers when npm pack

---

src/components/config/validation/validator/probe.test.ts
src/components/config/validation/validator/probe.ts

Fix alert assertion validation. This will resolves #1177.
- Add some tests.
- Compile alert assertion expression to the data with default value instead of empty array.
- Move manual validation into [Joi](https://github.com/hapijs/joi).
Run with the following configuration
```yaml
probes:
- id: "1"
requests:
- url: https://github.com
alerts:
- assertion: response.size >= 10000 ms
message: Response size is {{ response.size }}, expecting less than 10000
```
Use `response.size >= 10000 ms` as an alert assertion in a probe.
https://github.com/hyperjumptech/monika/assets/15191978/1689a58a-be59-41bf-89da-ad872e204204
https://github.com/hyperjumptech/monika/assets/15191978/4425d36d-ced9-446e-9c09-03933b46e3ec

Fix: Validation on Alert Assertion

---

.github/workflows/npm-notification-publish.yml
packages/notification/README.md

1. Solves #1192 
2. Publish to npm not triggering
1. Add wildcard to path trigger
reference: [Github document](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths)
2. Add more detail to README doc
h/t @raosan for the link

Tweak trigger to deploy notification package

---

.github/workflows/publish-snap.yml

1. Fixes issue #1191 
2. Out of date github/action use
1. The way snapcraft github/action passes authentication was updated
2. Now passing token via environment 
```yaml
- uses: snapcore/action-publish@v1
env:
SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
with:
snap: ${{ steps.snapcraft.outputs.snap }}
release: edge
```
```yaml
- uses: snapcore/action-publish@v1
with:
store_login: ${{ secrets.STORE_LOGIN }}
snap: ${{ steps.snapcraft.outputs.snap }}
release: edge
```
Reference: [snapcraft action docs](https://github.com/snapcore/action-publish)

Update Snapcraft pipeline

---

.github/workflows/publish-snap.yml

1. Fixes issue #1206 
2. Broken snapcraft pipeline
1. Add write permission for action (didn't have it before)
1. Testing using [github.com/nektos/act](https://github.com/nektos/act)
2. Run the "publish-snap.yml" locally

Fix broken snapcraft pipeline 

---

src/components/config/index.ts
src/symon/index.test.ts
src/symon/index.ts

Update probe data independently. It is an effort to resolves #1163.
1. Polling to Symon probe changes endpoint to get probe changes data.
2. Apply the probe changes based on the changes type.
1. Run Monika in Symon mode.
2. Add, update, delete a probe.
https://github.com/hyperjumptech/monika/assets/15191978/766a992f-f193-4926-84a0-003aa1bb6772

Refactor: Update Probe Data Independently

---

src/components/logger/history.ts

Fix wrong SQLite migration file path. It resolves #1216.
Revert the previous file changes.
Run `rm -rf monika-logs.db && npm start`.

Fix: Wrong SQLite Migration File Path

---

src/components/probe/prober/http/request.ts
src/symon/index.ts

1. This PR adds an `error` field when an error response exists
2. This PR changes result from `success` to `failed`
1. Run Monika with an invalid URL to get the error
4. Expectation: The error field must be sent

fix: missing send error field when an error response exists

---

package-lock.json
package.json

1. Update Oclif versions
1. Update `@oclif/core` to v3
2. Update `@oclif/plugin-help` to v6
3. Update `@oclif/plugin-version` to v2
1. `npm run prepack`
2. `npm run pack`
3. `npm i -g hyperjumptech-monika-1.16.3.tgz`
4. `monika`

Chore: Bump Oclif versions

---

src/symon/index.ts

Implement a multi-node Monika with a probe changes mechanism to update the probe.
The implementation checks for probe assignment data changes. If there are changes, Monika will re-fetch probe configuration data.
Run multiple instances of Monika in Symon mode. Run `npm start -- --symonUrl=[symonUrl] --symonKey=[symonKey] --symonLocationId=[symonLocationId] --symon-api-version=v2 --symonGetProbesIntervalMs=5000`.
https://github.com/hyperjumptech/monika/assets/15191978/0ef55d5a-eb75-4472-9294-d2aeb5919f56

Fix: Monika Multi Node

---

.github/workflows/auto-pr-schemastore.yml
.github/workflows/docker-release-from-tag.yml
.github/workflows/docs-build.yml
.github/workflows/docs.yml
.github/workflows/nightly-release.yml
.github/workflows/node.js.yml
.github/workflows/npm-notification-publish.yml
.github/workflows/npm-publish.yml
.github/workflows/publish-snap.yml
.github/workflows/upload-binary.yml
Dockerfile
Dockerfile.flyio
package-lock.json
package.json

1. Implements #1234 
2. Updating node to v20.x
1. Update all pipelines
2. Regenerate package.json
1. Pushing the branch here first to test the pipelines. All pipelines should be green
2. `npm run test` should all work without errors
(updated screenshot)

Update to Node to v20.x

---

docs/src/pages/guides/cli-options.md
src/commands/monika.ts
src/components/logger/startup-message.test.ts
src/components/logger/startup-message.ts
src/flag.ts

This PR resolves #1237 
1. Create `--experimental-fetch` as toggle feature flag to change HTTP client
1. Added new flag `--experimental-fetch`
2. Added new tests for startup message
1. `npm run test`
3. Compare startup message `npm run start` with `npm run start -- --experimental-fetch`

feat(native fetch): create --experimental-fetch as toggle feature

---

.eslintrc
CHANGELOG.md
package-lock.json
package.json

Release: Version 1.18.0

---

.github/workflows/docs-build.yml
.github/workflows/docs.yml

1. Solves #1244 
2. Fixes Doc building fails in pipeline
1. Using the `--legacy-peer-deps` switch to `npm` dependency install 
2. Revert npm to version 6 behaviour
1. `npm run test` should run without error
2. Trigger github action to  build the docs, by pushing to repository, or trigger the github action manually.
Before: Build failed
After: Build is successful

Tweak Docs Build Workflow

---

package-lock.json
package.json
src/components/config/parse-insomnia.ts
src/components/logger/startup-message.test.ts
src/components/logger/startup-message.ts
src/components/probe/prober/http/index.test.ts
src/components/probe/prober/http/request.ts
src/interfaces/request.ts
src/utils/http.ts

Fix failed tests when using fetch.
Implemented by mimicking Axios's implementation of HTTP requests.
1. Change `flags['native-fetch']` to `true` in [here](https://github.com/haricnugraha/monika/blob/e78b2e6224d1406545bf7548f916ff44d4eb05d4/src/components/probe/prober/http/request.ts#L97).
2. Run `npm test`.

Fix: Fetch Implementation

---

docs/src/pages/guides/tls-checkers.md
docs/src/pages/quick-start.md
packages/notification/channel/mailgun.ts
packages/notification/channel/smtp.ts
packages/notification/index.ts
packages/notification/package.json
packages/notification/utils/default-sender.ts
src/components/config/index.ts
src/components/logger/flush.test.ts
src/components/logger/history.ts
src/components/probe/prober/http/index.ts
src/jobs/tls-check.ts
src/utils/open-website.ts
src/utils/pino.ts

- Convert a TODO comment into an issue #1260. 
- Make the hardcoded notification sender changeable through a parameter.
- Separate sending error notification for the TLS checker function due to poor abstraction.
- Remove irrelevant TODO comments.
It will resolve #1010.
Run the following configuration. You should receive a TLS error notification (Please set your own notification):
```yaml
probes:
- id: example
requests:
- url: 'https://example.com'
certificate:
domains:
- example.com
- expired.badssl.com
reminder: 30
```

Refactor: Convert TODO Comments Into Issues

---

src/components/probe/prober/http/request.ts
src/interfaces/request.ts

This PR resolves #1263 
1. Fix crash caused by wrong typing
1. Revert #1256 for request config type of `HeadersInit` back to `object`
2. Revert HTTP prober related to type change
1. Unit test Axios HTTP prober with `npm run test`.
- Expect successful run.
2. Run Monika to test Symon client with `monika --symonUrl <URL> --symonKey <UUID> --follow-redirects=5 --retryInitialDelayMs=150000 --ignoreInvalidTLS`.
- Expect successful run with no crash happen.
3. Force Monika to use Node.js fetch `sed -i ".bak" "s/flags\[\'native\-fetch\'\]/true/g" "src/components/probe/prober/http/request.ts"`
4. Unit test Node.js fetch implementation `npm run test`
- Expect successful run.

fix(http prober): crash on request probe type

---

docs/src/pages/guides/probes.md
src/components/probe/prober/http/request.ts

This PR resolves #1266 
1. Handle axios error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE`
1. Map error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE` to error code 27
2. Map error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE` to error codename `ELEAFSIGNATURE`
3. Add documentation for error code 27
1. Create `monika.yml` config below
```yaml
probes:
- id: 'Example'
requests:
- url: https://kemendesa.go.id/
```
2. `npm run start -- -r 1`
3. On 5th failure, expect to see warning log `id:Example ERROR: EINVALIDLEAFSIGN: Unable to verify the first / leaf certificate., NOTIF: Service probably down`

fix(http): handle axios error code UNABLE_TO_VERIFY_LEAF_SIGNATURE

---

src/components/probe/prober/http/index.ts
src/components/probe/prober/http/request.test.ts
src/components/probe/prober/http/request.ts
src/utils/http.ts

This PR resolves #1268 
1. Handle HTTP status code 3xx for Node.js fetch implementation
1. Manually handle status code 3xx on Node.js fetch function
2. Move HTTP client's dependency to flag to parameter function
3. Add tests
1. `npm run test`
2. Create `monika.yml` config file below
```YAML
probes:
- id: 'Example'
requests:
- url: https://httpbin.org/redirect/3
timeout: 60000
interval: 5
alerts:
- assertion: response.time >= 60000
message: HTTP response time is {{ response.time }}, expecting 10000
```
3. `npm run start -- --native-fetch -c monika.yml -r 1`

feat(node.js fetch): #1268 implement redirect for fetch

---

package-lock.json
packages/notification/channel/monika-notif.ts
packages/notification/package.json

1. Implement `sendWithCustomContent` in monika-notif like #1109  
1. export types to be used in neosense
2. add `sendWithCustomContent` function to support [Neosense](https://neosense.bgnlab.id/)
1. run monika with [monika-notif](https://whatsapp.hyperjump.tech/?tab=register) notification config
3. check is monika running without error
4. get WhatsApp notif that monika is starting and nothing is broken

Feat: adding sendWithCustomContent in monika-notif

---

.github/workflows/publish-snap.yml
snapcraft.yaml

This PR resolves #1255 
1. Fix snap package job not including monika notification package
1. Extract tarball
2. Copy package/notification/lib/ content into extracted tarball path
3. Use extract path as snapcraft's build source
- Linux x64 platform
- Snapcraft build environment
Duplicate steps to build snap binary from `publish-snap.yml`
1. `npm ci --workspaces --if-present`
2. `npm run build --workspaces --if-present`
3. `npm ci`
4. `npm run pack-tarballs`
5. `mv dist/monika*.tar.gz dist/monika.tar.gz`
6. `tar -zvxf dist/monika.tar.gz -C dist/`
7. `cp -vr packages/notification/lib/* dist/monika/packages/notification/`
8. `snapcraft`
9. `sudo snap install monika*.snap --devmode`
10. Confirm monika bin location by `which monika`
11. Copy config from #1255 
12. `monika -r 1`

fix(snap) : #1255 fix notification not included in snap binary

---

docs/src/pages/tutorial/run-using-ping-method.md
monika.example.yml
src/components/logger/startup-message.ts
src/components/probe/prober/http/request.ts
src/components/probe/prober/icmp/request.ts
src/monika-config-schema.json

This PR is a deprecation step before removing ping from HTTP probe. See #1260 
1. Remove `"ping: true"` from `monika-config-schema.json`
2. Add deprecation warning to startup message
3. Add deprecation warning to HTTP probe message
4. Update ping tutorial
5. Update `monika.yml` sample
1. Setup monika configuration below
```
probes:
- id: 'ping_test'
name: ping_test
description: requesting icmp ping
interval: 10
requests:
- url: http://google.com
ping: true
alerts:
message: response status message
```
2. `npm run start -- -r 1`
3. Expected screenshot below

feat(ping): #1260 deprecate ping request

---

docs/src/pages/quick-start.md
docs/src/pages/tutorial/run-in-docker.md

This PR resolves #1289 
1. Add docker guide for apple silicon
1. Add docker instruction on Quick Start Guide
2. Add `--platform linux/amd64` on Monika docker tutorial
1. `cd docs`
2. `npm ci --legacy-peer-deps`
3. `npm run dev`
4. Visit `http://localhost:3000/quick-start`
5. Visit `http://localhost:3000/tutorial/run-in-docker`

chore(docs): #1289 add docker guide for apple silicon

---

src/components/config/__tests__/expected.textfile.yml
src/components/config/parser/text.ts
src/components/probe/prober/http/request.test.ts
src/components/probe/prober/http/request.ts
src/interfaces/request.ts
src/symon/index.test.ts

Fix Monika sends `null` request body as `"null"`.
1. Add a test.
2. Change the request body type.
3. Remove the non string body conversion using `JSON.stringify` that caused `null` becomes `"null"`.
Run Monika with the following configuration:
```yaml
probes:
- id: '1'
interval: 1
requests:
- url: https://idp.sinarmas.com/api/health
body: null
```
[output.webm](https://github.com/hyperjumptech/monika/assets/15191978/64f5bae5-247a-4fc6-8764-213da6207519)

Fix: Monika sends null request body as string null

---

docs/src/pages/guides/cli-options.md
docs/src/pages/guides/probes.md
package-lock.json
package.json
src/components/probe/prober/http/index.ts
src/components/probe/prober/http/request.ts
src/components/probe/prober/http/response-cache.ts
src/flag.ts

This PR resolves #1285 
1. Added new file `src/components/probe/prober/http/response-cache.ts` : in-memory cache for HTTP response
1. Create in-memory cache with `@isaac/ttl-cache`
2. Changed `HTTPProber` to use cached response on first probing attempt
3. Added new CLI option `--ttl-cache` to set cache's time-to-live
4. Added new CLI option `--verbose-cache` to monitor cache use
1. `npm run start -- --verbose-cache`
2. Observe messages for `Cache HIT` and `Cache MISS`

feat(http prober): #1285 implement cache http response

---

dev/docker-compose.yaml
docs/src/pages/guides/cli-options.md
src/components/probe/prober/http/index.ts
src/components/probe/prober/http/response-cache.ts
src/flag.ts

Disable cache by default.
Change the default value of the `ttl-cache` flag.
1. Run `docker compose -f ./dev/docker-compose.yaml up httpbin`.
2. Run `npm start` with the following configuration.
```yaml
probes:
- id: '1'
requests:
- url: http://localhost:3002/status/200
interval: 3
```
3. Stop the docker compose command from the step one.
4. Re-run the docker compose command from the step one.
https://github.com/hyperjumptech/monika/assets/15191978/82f64438-879c-4abf-90b8-560da9d0fc8a
https://github.com/hyperjumptech/monika/assets/15191978/77fbcd82-6465-4d25-a163-8000064f70d2

Feat: Disable Cache by Default

---

src/components/probe/prober/http/request.ts

This PR handles CERT_HAS_EXPIRED error #1298 
1. Map the CERT_HAS_EXPIRED to status code 18
Use this config:
```yaml
probes:
- id: '1'
name: 'Coding Horror'
description: 'Probe to check Coding Horror blog'
interval: 10 # in seconds (every 10 minutes)
requests:
- method: GET
url: 'https://expired.badssl.com'
alerts: 
message: Status not 200
```

Feat: Handle CERT_HAS_EXPIRED error

---

.dockerignore
Dockerfile

1.  [Issue-1301](https://github.com/hyperjumptech/monika/issues/1301)
1. Added a line in the .dockerignore file to prevent `packages/notification/node_modules` from being copied into the docker container build stage. Please refer to the explanation below
2. Added command to add python3, py3-setuptools, make, and gcc as the dependencies of sqlite3 rebuilding needed by monika notifications.
1. Clone the project
2. Issue a `npm run build -w packages/notification/` to build dependencies packages
3. Issue a `npm ci` to pull dependencies
4. Issue a `make docker` at the project root
The [line](https://github.com/hyperjumptech/monika/blob/05370493a2c5be10f3d2376148717951ba6c6937/Dockerfile#L13) and .dockerignore file allow the content of `packages/notification/node_modules` directory on the host …

Reproduce 1301

---

src/components/probe/prober/http/request.ts

#1327 
1. Added handler to set the allowUnauthorized value for HTTP Fetcher from --ignoreInvalidTLS flag
1. Create a config:
```yml
probes:
- id: '1'
name: Example
interval: 10
requests:
- url: https://www.banksinarmas.com/PersonalBanking/loginCustomer.do
method: GET
notifications:
- id: '1'
type: desktop
```
3. Run `npm run start`
4. It should fail saying ELEAFSIGNATURE
5. Stop Monika and run `npm run start -- --ignoreInvalidTLS`
6. It should successfully probe

Fix: Allow --ignoreInvalidTLS flag to override allowUnauthorized value

---

src/components/probe/prober/http/index.ts
src/components/probe/prober/http/request.ts
src/utils/http.ts

This PR fixes #1327
1. Moved the assignment for getContext().flags.ignoreInvalidTLS to [src/components/probe/prober/http/index.ts](https://github.com/hyperjumptech/monika/compare/issue/1327?expand=1#diff-537950d0505c20b7b3ec67590102fdafdbbbbddb0130d5dbf7a4ac232060598d)
2. Create agent for insecure HTTPS 
Using this config:
```yaml
probes:
- id: '1'
name: Example
interval: 3
requests:
- url: https://www.banksinarmas.com/PersonalBanking/loginCustomer.do
method: GET
notifications:
- id: '1'
type: desktop
```
1. In src/components/probe/prober/http/request.ts, add this in line 81
log.info(`Doing HTTP Request with options: ${JSON.stringify(requestConfig)}`)
2. Run monika using `npm run start`
3. Run Monika using `npm run start -- --ignoreInvalidTLS`
Previously failed insecure request
Without …

Fix: --ignoreInvalidTLS has no effect

---

docs/src/pages/guides/cli-options.md
src/commands/monika.ts
src/components/logger/startup-message.test.ts
src/components/logger/startup-message.ts
src/flag.ts

1. Implements #1332 
2. Bypass startup messages 
3. Bypass startup notification ("Monika is started" notification)
1. Add a switch `--skip-start-message` to bypass greetings and startup info messages
1. Use the following test.yaml config: 
```yaml
probes:
- id: 'http-1'
name: 'status-200-test'
requests:
- url: https://httpbin.org/status/401
method: PATCH
alerts:
- assertion: response.status < 200 or response.status > 308
message: HTTP Status is not 200
- assertion: response.time > 2000
message: Too sloow
```
2. Run monika with the switch `npm start -- -c test.yaml --skip-start-message` 
3. Expect monika to start probing without greeting and startup messages
4. Expect no startup notification is sent
After PR
Before PR

Feat[1332] : Skip startup message

---

src/commands/monika.ts
src/components/config/index.test.ts
src/components/config/sanitize.ts
src/looper/index.ts

This PR resolves #1330 
1. Move probe handling logic from monika.ts to config component
2. Add probe sanitization during config validation
3. Add tests for config sanitization
4. Make failed request assertion ID deterministic
1. Create following config
```
probes:
- id: 'http-1'
name: 'status-401-test'
requests:
- url: https://httpbin.org/status/401
method: PATCH
alerts:
- assertion: response.status < 200 or response.status > 308
message: HTTP Status is not 200
- assertion: response.ime > 2000
message: Too sloow
```
2. `npm run start -- --config monika.yml`
3. Observe log `WARN: 2025-01-05T10:30:46.044Z 1 id:http-1 ERROR: ECONNREFUSED: Attempted to connect to a server, but the server declined the connection. Ensure the server is running and accepting connections., NOTIF: Service probably …

fix: failed request assertion not found
